number:
  - platform: toptronic
    name: Normal-Raumtemperatur Heizbetrieb (1)
    device_type: WEZ
    function_group: 1
    function_number: 0
    datapoint: 3051
    id: WEZ_1_0_3051_set
    type: S16
    min_value: 100
    max_value: 300
    step: 5
    decimal: 1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
  - platform: toptronic
    name: Spar-Raumtemperatur Heizbetrieb (1)
    device_type: WEZ
    function_group: 1
    function_number: 0
    datapoint: 3053
    id: WEZ_1_0_3053_set
    type: S16
    min_value: 50
    max_value: 200
    step: 5
    decimal: 1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
  - platform: toptronic
    name: Normal-Raumtemperatur Heizbetrieb (2)
    device_type: WEZ
    function_group: 1
    function_number: 1
    datapoint: 3051
    id: WEZ_1_1_3051_set
    type: S16
    min_value: 100
    max_value: 300
    step: 5
    decimal: 1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
  - platform: toptronic
    name: Spar-Raumtemperatur Heizbetrieb (2)
    device_type: WEZ
    function_group: 1
    function_number: 1
    datapoint: 3053
    id: WEZ_1_1_3053_set
    type: S16
    min_value: 50
    max_value: 200
    step: 5
    decimal: 1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
  - platform: toptronic
    name: Normal-Raumtemperatur Heizbetrieb (3)
    device_type: WEZ
    function_group: 1
    function_number: 2
    datapoint: 3051
    id: WEZ_1_2_3051_set
    type: S16
    min_value: 100
    max_value: 300
    step: 5
    decimal: 1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
  - platform: toptronic
    name: Spar-Raumtemperatur Heizbetrieb (3)
    device_type: WEZ
    function_group: 1
    function_number: 2
    datapoint: 3053
    id: WEZ_1_2_3053_set
    type: S16
    min_value: 50
    max_value: 200
    step: 5
    decimal: 1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
  - platform: toptronic
    name: Normal-Warmwassertemperatur
    device_type: WEZ
    function_group: 2
    function_number: 0
    datapoint: 5051
    id: WEZ_2_0_5051_set
    type: S16
    min_value: 100
    max_value: 700
    step: 10
    decimal: 1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
  - platform: toptronic
    name: Spar-Warmwassertemperatur
    device_type: WEZ
    function_group: 2
    function_number: 0
    datapoint: 5086
    id: WEZ_2_0_5086_set
    type: U8
    min_value: 10
    max_value: 70
    step: 1
    decimal: 0
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
  - platform: toptronic
    name: Smart-Grid (Offset) WW-Sollwert
    device_type: WEZ
    function_group: 2
    function_number: 0
    datapoint: 5077
    id: WEZ_2_0_5077_set
    type: S16
    min_value: 0
    max_value: 800
    step: 5
    decimal: 1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-kelvin
    device_class: temperature
  - platform: toptronic
    name: SmartGrid Offset Raum-Sollw. Heizen (1)
    device_type: WEZ
    function_group: 1
    function_number: 0
    datapoint: 7031
    id: WEZ_1_0_7031_set
    type: S16
    min_value: 0
    max_value: 120
    step: 5
    decimal: 1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-kelvin
    device_class: temperature
  - platform: toptronic
    name: SmartGrid Offset Raum-Sollw. Heizen (2)
    device_type: WEZ
    function_group: 1
    function_number: 1
    datapoint: 7031
    id: WEZ_1_1_7031_set
    type: S16
    min_value: 0
    max_value: 120
    step: 5
    decimal: 1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-kelvin
    device_class: temperature
  - platform: toptronic
    name: SmartGrid Offset Raum-Sollw. Heizen (3)
    device_type: WEZ
    function_group: 1
    function_number: 2
    datapoint: 7031
    id: WEZ_1_2_7031_set
    type: S16
    min_value: 0
    max_value: 120
    step: 5
    decimal: 1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-kelvin
    device_class: temperature
  - platform: toptronic
    name: "SmartGrid Offset Raum-Sollw. K\xFChlen (1)"
    device_type: WEZ
    function_group: 1
    function_number: 0
    datapoint: 7046
    id: WEZ_1_0_7046_set
    type: S16
    min_value: -600
    max_value: 0
    step: 1
    decimal: 1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-kelvin
    device_class: temperature
  - platform: toptronic
    name: "SmartGrid Offset Raum-Sollw. K\xFChlen (2)"
    device_type: WEZ
    function_group: 1
    function_number: 1
    datapoint: 7046
    id: WEZ_1_1_7046_set
    type: S16
    min_value: -600
    max_value: 0
    step: 1
    decimal: 1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-kelvin
    device_class: temperature
select:
  - platform: toptronic
    name: Betriebswahl Heizung (1)
    device_type: WEZ
    function_group: 1
    function_number: 0
    datapoint: 3050
    id: WEZ_1_0_3050_set
    options:
      - Standby
      - Woche 1
      - Woche 2
      - Konstant
      - Sparbetrieb
      - Handbetrieb Heizen
      - "Handbetrieb K\xFChlen"
    values:
      - 0
      - 1
      - 2
      - 4
      - 5
      - 7
      - 8
  - platform: toptronic
    name: Betriebswahl Heizung (2)
    device_type: WEZ
    function_group: 1
    function_number: 1
    datapoint: 3050
    id: WEZ_1_1_3050_set
    options:
      - Standby
      - Woche 1
      - Woche 2
      - Konstant
      - Sparbetrieb
      - Handbetrieb Heizen
      - "Handbetrieb K\xFChlen"
    values:
      - 0
      - 1
      - 2
      - 4
      - 5
      - 7
      - 8
  - platform: toptronic
    name: Betriebswahl Heizung (3)
    device_type: WEZ
    function_group: 1
    function_number: 2
    datapoint: 3050
    id: WEZ_1_2_3050_set
    options:
      - Standby
      - Woche 1
      - Woche 2
      - Konstant
      - Sparbetrieb
      - Handbetrieb Heizen
      - "Handbetrieb K\xFChlen"
    values:
      - 0
      - 1
      - 2
      - 4
      - 5
      - 7
      - 8
  - platform: toptronic
    name: Betriebswahl Warmwasser
    device_type: WEZ
    function_group: 2
    function_number: 0
    datapoint: 5050
    id: WEZ_2_0_5050_set
    options:
      - Standby
      - Woche 1
      - Woche 2
      - Konstant
      - Sparbetrieb
    values:
      - 0
      - 1
      - 2
      - 4
      - 6
  - platform: toptronic
    name: "Betriebswahl W\xE4rmeerzeuger"
    device_type: WEZ
    function_group: 10
    function_number: 1
    datapoint: 9075
    id: WEZ_10_1_9075_set
    options:
      - Deakt.
      - Automatik
      - Heizen
      - "K\xFChlen"
    values:
      - 0
      - 1
      - 4
      - 5
  - platform: toptronic
    name: "Smart Grid \xFCber Systembus"
    device_type: WEZ
    function_group: 0
    function_number: 0
    datapoint: 38012
    id: WEZ_0_0_38012_set
    options:
      - Normal
      - Vorzugbetrieb
      - Gesperrt
      - Abnahmezwang
    values:
      - 0
      - 1
      - 2
      - 3
  - platform: toptronic
    name: "Ausl\xF6ser Smart Grid Funktion"
    device_type: WEZ
    function_group: 0
    function_number: 0
    datapoint: 38013
    id: WEZ_0_0_38013_set
    options:
      - Aus
      - Eingangskontakte
      - Systembus
      - "Leistung ged\xE4mpft"
    values:
      - 0
      - 1
      - 2
      - 3
