sensor:
  - platform: toptronic
    name: "AF1 - Aussenf\xFChler 1"
    device_type: WEZ
    function_group: 0
    function_number: 0
    datapoint: 0
    id: WEZ_0_0_0
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
  - platform: toptronic
    name: Normal-Raumtemperatur Heizbetrieb (1)
    device_type: WEZ
    function_group: 1
    function_number: 0
    datapoint: 3051
    id: WEZ_1_0_3051
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
    internal: true
  - platform: toptronic
    name: Spar-Raumtemperatur Heizbetrieb (1)
    device_type: WEZ
    function_group: 1
    function_number: 0
    datapoint: 3053
    id: WEZ_1_0_3053
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
    internal: true
  - platform: toptronic
    name: Normal-Raumtemperatur Heizbetrieb (2)
    device_type: WEZ
    function_group: 1
    function_number: 1
    datapoint: 3051
    id: WEZ_1_1_3051
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
    internal: true
  - platform: toptronic
    name: Spar-Raumtemperatur Heizbetrieb (2)
    device_type: WEZ
    function_group: 1
    function_number: 1
    datapoint: 3053
    id: WEZ_1_1_3053
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
    internal: true
  - platform: toptronic
    name: Normal-Raumtemperatur Heizbetrieb (3)
    device_type: WEZ
    function_group: 1
    function_number: 2
    datapoint: 3051
    id: WEZ_1_2_3051
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
    internal: true
  - platform: toptronic
    name: Spar-Raumtemperatur Heizbetrieb (3)
    device_type: WEZ
    function_group: 1
    function_number: 2
    datapoint: 3053
    id: WEZ_1_2_3053
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
    internal: true
  - platform: toptronic
    name: Normal-Warmwassertemperatur
    device_type: WEZ
    function_group: 2
    function_number: 0
    datapoint: 5051
    id: WEZ_2_0_5051
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
    internal: true
  - platform: toptronic
    name: Spar-Warmwassertemperatur
    device_type: WEZ
    function_group: 2
    function_number: 0
    datapoint: 5086
    id: WEZ_2_0_5086
    type: U8
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
    internal: true
  - platform: toptronic
    name: Warmwasser-Soll
    device_type: WEZ
    function_group: 2
    function_number: 0
    datapoint: 1004
    id: WEZ_2_0_1004
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
  - platform: toptronic
    name: Warmwasser-Ist SF
    device_type: WEZ
    function_group: 2
    function_number: 0
    datapoint: 4
    id: WEZ_2_0_4
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
  - platform: toptronic
    name: Vorlauf-Ist (1)
    device_type: WEZ
    function_group: 1
    function_number: 0
    datapoint: 2
    id: WEZ_1_0_2
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
  - platform: toptronic
    name: Vorlauf-Ist (2)
    device_type: WEZ
    function_group: 1
    function_number: 1
    datapoint: 2
    id: WEZ_1_1_2
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
  - platform: toptronic
    name: Vorlauf-Ist (3)
    device_type: WEZ
    function_group: 1
    function_number: 2
    datapoint: 2
    id: WEZ_1_2_2
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
  - platform: toptronic
    name: WEZ-Leistung
    device_type: WEZ
    function_group: 60
    function_number: 254
    datapoint: 30
    id: WEZ_60_254_30
    type: U8
    unit_of_measurement: '%'
    icon: mdi:percent
    device_class: power_factor
    state_class: measurement
  - platform: toptronic
    name: Elektrische Gesamtenergie WEZ MWh
    device_type: WEZ
    function_group: 10
    function_number: 1
    datapoint: 23009
    id: WEZ_10_1_23009
    type: U32
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
    unit_of_measurement: MWh
    icon: mdi:flash
    device_class: energy
    state_class: measurement
  - platform: toptronic
    name: "W\xE4rmemenge Heizen"
    device_type: WEZ
    function_group: 60
    function_number: 254
    datapoint: 47
    id: WEZ_60_254_47
    type: U32
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
    unit_of_measurement: MWh
    icon: mdi:flash
    device_class: energy
    state_class: measurement
  - platform: toptronic
    name: "W\xE4rmemenge WW"
    device_type: WEZ
    function_group: 60
    function_number: 254
    datapoint: 55
    id: WEZ_60_254_55
    type: U32
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
    unit_of_measurement: MWh
    icon: mdi:flash
    device_class: energy
    state_class: measurement
  - platform: toptronic
    name: Smart-Grid (Offset) WW-Sollwert
    device_type: WEZ
    function_group: 2
    function_number: 0
    datapoint: 5077
    id: WEZ_2_0_5077
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-kelvin
    device_class: temperature
    state_class: measurement
    internal: true
  - platform: toptronic
    name: SmartGrid Offset Raum-Sollw. Heizen (1)
    device_type: WEZ
    function_group: 1
    function_number: 0
    datapoint: 7031
    id: WEZ_1_0_7031
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-kelvin
    device_class: temperature
    state_class: measurement
    internal: true
  - platform: toptronic
    name: SmartGrid Offset Raum-Sollw. Heizen (2)
    device_type: WEZ
    function_group: 1
    function_number: 1
    datapoint: 7031
    id: WEZ_1_1_7031
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-kelvin
    device_class: temperature
    state_class: measurement
    internal: true
  - platform: toptronic
    name: SmartGrid Offset Raum-Sollw. Heizen (3)
    device_type: WEZ
    function_group: 1
    function_number: 2
    datapoint: 7031
    id: WEZ_1_2_7031
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-kelvin
    device_class: temperature
    state_class: measurement
    internal: true
  - platform: toptronic
    name: "SmartGrid Offset Raum-Sollw. K\xFChlen (1)"
    device_type: WEZ
    function_group: 1
    function_number: 0
    datapoint: 7046
    id: WEZ_1_0_7046
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-kelvin
    device_class: temperature
    state_class: measurement
    internal: true
  - platform: toptronic
    name: "SmartGrid Offset Raum-Sollw. K\xFChlen (2)"
    device_type: WEZ
    function_group: 1
    function_number: 1
    datapoint: 7046
    id: WEZ_1_1_7046
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-kelvin
    device_class: temperature
    state_class: measurement
    internal: true
text_sensor:
  - platform: toptronic
    name: Betriebswahl Heizung (1)
    device_type: WEZ
    function_group: 1
    function_number: 0
    datapoint: 3050
    id: WEZ_1_0_3050
    options:
      - Standby
      - Woche 1
      - Woche 2
      - Konstant
      - Sparbetrieb
      - Handbetrieb Heizen
      - "Handbetrieb K\xFChlen"
    values:
      - 0
      - 1
      - 2
      - 4
      - 5
      - 7
      - 8
  - platform: toptronic
    name: Betriebswahl Heizung (2)
    device_type: WEZ
    function_group: 1
    function_number: 1
    datapoint: 3050
    id: WEZ_1_1_3050
    options:
      - Standby
      - Woche 1
      - Woche 2
      - Konstant
      - Sparbetrieb
      - Handbetrieb Heizen
      - "Handbetrieb K\xFChlen"
    values:
      - 0
      - 1
      - 2
      - 4
      - 5
      - 7
      - 8
  - platform: toptronic
    name: Betriebswahl Heizung (3)
    device_type: WEZ
    function_group: 1
    function_number: 2
    datapoint: 3050
    id: WEZ_1_2_3050
    options:
      - Standby
      - Woche 1
      - Woche 2
      - Konstant
      - Sparbetrieb
      - Handbetrieb Heizen
      - "Handbetrieb K\xFChlen"
    values:
      - 0
      - 1
      - 2
      - 4
      - 5
      - 7
      - 8
  - platform: toptronic
    name: Betriebswahl Warmwasser
    device_type: WEZ
    function_group: 2
    function_number: 0
    datapoint: 5050
    id: WEZ_2_0_5050
    options:
      - Standby
      - Woche 1
      - Woche 2
      - Konstant
      - Sparbetrieb
    values:
      - 0
      - 1
      - 2
      - 4
      - 6
  - platform: toptronic
    name: Status Heizkreisregelung (1)
    device_type: WEZ
    function_group: 1
    function_number: 0
    datapoint: 2051
    id: WEZ_1_0_2051
    options:
      - Abgeschaltet
      - Heizen normal
      - Heizen Komfort
      - Heizen Eco
      - Frostschutz
      - Ferien
      - Party
      - "K\xFChlen normal"
      - "K\xFChlen Komfort"
      - "K\xFChlen Eco"
      - "ST\xD6RUNG"
      - Handbetrieb
      - "Schutz-K\xFChlbetrieb"
      - "K\xFChlen extern/konstant"
      - Heizen extern/konstant
      - SmartGrid-Vorzug
    values:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 22
      - 23
      - 26
  - platform: toptronic
    name: Status Heizkreisregelung (2)
    device_type: WEZ
    function_group: 1
    function_number: 1
    datapoint: 2051
    id: WEZ_1_1_2051
    options:
      - Abgeschaltet
      - Heizen normal
      - Heizen Komfort
      - Heizen Eco
      - Frostschutz
      - Ferien
      - Party
      - "K\xFChlen normal"
      - "K\xFChlen Komfort"
      - "K\xFChlen Eco"
      - "ST\xD6RUNG"
      - Handbetrieb
      - "Schutz-K\xFChlbetrieb"
      - "K\xFChlen extern/konstant"
      - Heizen extern/konstant
      - SmartGrid-Vorzug
    values:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 22
      - 23
      - 26
  - platform: toptronic
    name: Status Warmwasserregelung
    device_type: WEZ
    function_group: 2
    function_number: 0
    datapoint: 2052
    id: WEZ_2_0_2052
    options:
      - Aus
      - Laden normal
      - Laden Komfort
      - "ST\xD6RUNG"
      - Zapfung
      - Laden reduziert
      - SmartGrid-Vorzug
      - SmartGrid-Zwang
    values:
      - 0
      - 1
      - 2
      - 5
      - 6
      - 8
      - 12
      - 13
  - platform: toptronic
    name: Betriebsstatus
    device_type: WEZ
    function_group: 60
    function_number: 254
    datapoint: 34
    id: WEZ_60_254_34
    options:
      - Aus
      - Heizen
      - "Aktiv-K\xFChlen"
      - Sperre
      - WW-Laden
      - Frostschutz
      - WEZ-Temp zu tief
      - VL zu hoch
      - Abtauen
      - "Passiv-K\xFChlen"
      - "Hochdruck-St\xF6rung"
      - "Niederdruck-St\xF6rung"
      - Wiederanlauf
      - EVU-Sperre
      - Vorlaufzeit
      - Nachlaufzeit
      - MOP
      - Abtauung erfolglos
      - Kondensatorpumpe
      - "Inverter-St\xF6rung"
      - "\xD6lvorw\xE4rmung"
      - Kaltstart
    values:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 11
      - 12
      - 16
      - 17
      - 18
      - 19
      - 44
      - 49
      - 51
      - 55
      - 97
      - 98
  - platform: toptronic
    name: "Betriebswahl W\xE4rmeerzeuger"
    device_type: WEZ
    function_group: 10
    function_number: 1
    datapoint: 9075
    id: WEZ_10_1_9075
    options:
      - Deakt.
      - Automatik
      - Heizen
      - "K\xFChlen"
    values:
      - 0
      - 1
      - 4
      - 5
  - platform: toptronic
    name: "Status K\xFChlventil aktiv UKA"
    device_type: WEZ
    function_group: 3
    function_number: 0
    datapoint: 22024
    id: WEZ_3_0_22024
    options:
      - zu
      - offen
    values:
      - 0
      - 1
  - platform: toptronic
    name: Status Smart Grid
    device_type: WEZ
    function_group: 0
    function_number: 0
    datapoint: 21090
    id: WEZ_0_0_21090
    options:
      - Normal
      - Vorzugbetrieb
      - Gesperrt
      - Abnahmezwang
      - inaktiv
    values:
      - 0
      - 1
      - 2
      - 3
      - 255
  - platform: toptronic
    name: "Smart Grid \xFCber Systembus"
    device_type: WEZ
    function_group: 0
    function_number: 0
    datapoint: 38012
    id: WEZ_0_0_38012
    options:
      - Normal
      - Vorzugbetrieb
      - Gesperrt
      - Abnahmezwang
    values:
      - 0
      - 1
      - 2
      - 3
  - platform: toptronic
    name: "Ausl\xF6ser Smart Grid Funktion"
    device_type: WEZ
    function_group: 0
    function_number: 0
    datapoint: 38013
    id: WEZ_0_0_38013
    options:
      - Aus
      - Eingangskontakte
      - Systembus
      - "Leistung ged\xE4mpft"
    values:
      - 0
      - 1
      - 2
      - 3
