#pragma once

#include "esphome/core/component.h"
#include "esphome/core/defines.h"
#include "esphome/core/log.h"
#include "esphome/components/sensor/sensor.h"
#include "esphome/components/text_sensor/text_sensor.h"
#include "esphome/components/uart/uart.h"

#include "mbus.h"
#include "dlms.h"
#include "obis.h"

#include <vector>

namespace esphome {
namespace dlms_meter {

static constexpr const char *DLMS_METER_VERSION = "1.0.0";
static constexpr const char *TAG = "dlms_meter";

// DLMS_METER_**_LIST generated by ESPHome and written in esphome/core/defines

#if !defined(DLMS_METER_SENSOR_LIST) && !defined(DLMS_METER_TEXT_SENSOR_LIST)
// Neither set, set it to a dummy value to not break build
#define DLMS_METER_TEXT_SENSOR_LIST(F, SEP)
#endif

#if defined(DLMS_METER_SENSOR_LIST) && defined(DLMS_METER_TEXT_SENSOR_LIST)
#define DLMS_METER_BOTH ,
#else
#define DLMS_METER_BOTH
#endif

#ifndef DLMS_METER_SENSOR_LIST
#define DLMS_METER_SENSOR_LIST(F, SEP)
#endif

#ifndef DLMS_METER_TEXT_SENSOR_LIST
#define DLMS_METER_TEXT_SENSOR_LIST(F, SEP)
#endif

#define DLMS_METER_DATA_SENSOR(s) s
#define DLMS_METER_COMMA ,

struct MeterData {
  float voltage_l1;             // Voltage L1
  float voltage_l2;             // Voltage L2
  float voltage_l3;             // Voltage L3
  float current_l1;             // Current L1
  float current_l2;             // Current L2
  float current_l3;             // Current L3
  float active_power_plus;      // Active power taken from grid
  float active_power_minus;     // Active power put into grid
  float active_energy_plus;     // Active energy taken from grid
  float active_energy_minus;    // Active energy put into grid
  float reactive_energy_plus;   // Reactive energy taken from grid
  float reactive_energy_minus;  // Reactive energy put into grid
  std::string timestamp;        // Text sensor for the timestamp value

  // Netz NOE
  float power_factor;       // Power Factor
  std::string meternumber;  // Text sensor for the meterNumber value
};

/*
 * Provider constants
 */

enum Providers : uint32_t { PROVIDER_GENERIC = 0x00, PROVIDER_NETZNOE = 0x01 };

class DlmsMeterComponent : public Component, public uart::UARTDevice {
 public:
  DlmsMeterComponent() = default;

  void setup() override;
  void dump_config() override;
  void loop() override;

  void set_decryption_key(const uint8_t *decryption_key, size_t decryption_key_length);
  void set_provider(uint32_t provider);

  void publish_sensors(MeterData &data) {
#define DLMS_METER_PUBLISH_SENSOR(s) \
  if (this->s##_sensor_ != nullptr) \
    s##_sensor_->publish_state(data.s);
    DLMS_METER_SENSOR_LIST(DLMS_METER_PUBLISH_SENSOR, )

#define DLMS_METER_PUBLISH_TEXT_SENSOR(s) \
  if (this->s##_text_sensor_ != nullptr) \
    s##_text_sensor_->publish_state(data.s);
    // s##_text_sensor_->publish_state(data.s.c_str());
    DLMS_METER_TEXT_SENSOR_LIST(DLMS_METER_PUBLISH_TEXT_SENSOR, )
  }

  DLMS_METER_SENSOR_LIST(SUB_SENSOR, )
  DLMS_METER_TEXT_SENSOR_LIST(SUB_TEXT_SENSOR, )

 protected:
  bool parse_mbus_(std::vector<uint8_t> &mbus_payload);
  bool parse_dlms_(const std::vector<uint8_t> &mbus_payload, uint16_t &message_length, uint8_t &systitle_length,
                   uint16_t &header_offset);
  bool decrypt_(const std::vector<uint8_t> &mbus_payload, uint16_t message_length, uint8_t systitle_length,
                uint16_t header_offset, uint8_t *plaintext);
  void decode_obis_(uint8_t *plaintext, uint16_t message_length);

  std::vector<uint8_t> receive_buffer_;  // Stores the packet currently being received
  uint32_t last_read_ = 0;               // Timestamp when data was last read
  uint32_t read_timeout_ = 1000;         // Time to wait after last byte before considering data complete

  uint32_t provider_ = PROVIDER_GENERIC;  // Provider of the meter / your grid operator
  uint8_t decryption_key_[16];            // Stores the decryption key
  size_t decryption_key_length_;          // Stores the decryption key length (usually 16 bytes)

  uint16_t swap_uint16_(uint16_t val);
  uint32_t swap_uint32_(uint32_t val);
  void log_packet_(const std::vector<uint8_t> &data);
  void abort_();
};

}  // namespace dlms_meter
}  // namespace esphome
