"""ESP-IDF direct build generator for ESPHome."""

from esphome.components.esp32 import get_esp32_variant
from esphome.core import CORE
from esphome.helpers import mkdir_p, write_file_if_changed


def get_project_cmakelists() -> str:
    """Generate the top-level CMakeLists.txt for ESP-IDF project."""
    # Get IDF target from ESP32 variant (e.g., ESP32S3 -> esp32s3)
    variant = get_esp32_variant()
    idf_target = variant.lower().replace("-", "")

    return f"""\
# Auto-generated by ESPHome
cmake_minimum_required(VERSION 3.16)

set(IDF_TARGET {idf_target})
set(EXTRA_COMPONENT_DIRS ${{CMAKE_SOURCE_DIR}}/src)

include($ENV{{IDF_PATH}}/tools/cmake/project.cmake)
project({CORE.name})
"""


def get_component_cmakelists() -> str:
    """Generate the main component CMakeLists.txt."""
    # Common ESP-IDF components required by ESPHome
    idf_requires = [
        "app_update",
        "driver",
        "efuse",
        "esp_event",
        "esp_netif",
        "esp_partition",
        "esp_psram",
        "esp_rom",
        "esp_system",
        "esp_timer",
        "esp_wifi",
        "freertos",
        "heap",
        "log",
        "lwip",
        "mbedtls",
        "nvs_flash",
        "spi_flash",
        "wpa_supplicant",
    ]

    # Optional components that may not exist on all targets
    optional_requires = [
        "esp_adc",
        "esp_eth",
        "mdns",
        "mqtt",
    ]

    requires_str = " ".join(idf_requires)
    optional_str = "\n".join(
        f'if(TARGET idf::{comp})\n  list(APPEND opt_requires "{comp}")\nendif()'
        for comp in optional_requires
    )

    # Extract compile definitions from build flags (-DXXX -> XXX)
    compile_defs = [flag[2:] for flag in CORE.build_flags if flag.startswith("-D")]
    compile_defs_str = "\n    ".join(compile_defs) if compile_defs else ""

    return f"""\
# Auto-generated by ESPHome
file(GLOB_RECURSE app_sources
    "${{CMAKE_CURRENT_SOURCE_DIR}}/*.cpp"
    "${{CMAKE_CURRENT_SOURCE_DIR}}/*.c"
    "${{CMAKE_CURRENT_SOURCE_DIR}}/esphome/*.cpp"
    "${{CMAKE_CURRENT_SOURCE_DIR}}/esphome/*.c"
)

# Optional ESP-IDF components (may not exist on all targets)
set(opt_requires "")
{optional_str}

idf_component_register(
    SRCS ${{app_sources}}
    INCLUDE_DIRS "." "esphome"
    REQUIRES {requires_str}
    PRIV_REQUIRES ${{opt_requires}}
)

# Apply C++ standard
target_compile_features(${{COMPONENT_LIB}} PUBLIC cxx_std_20)

# ESPHome compile definitions
target_compile_definitions(${{COMPONENT_LIB}} PUBLIC
    {compile_defs_str}
)
"""


def write_project() -> None:
    """Write ESP-IDF project files."""
    mkdir_p(CORE.build_path)
    mkdir_p(CORE.relative_src_path())

    # Write top-level CMakeLists.txt
    write_file_if_changed(
        CORE.relative_build_path("CMakeLists.txt"),
        get_project_cmakelists(),
    )

    # Write component CMakeLists.txt in src/
    write_file_if_changed(
        CORE.relative_src_path("CMakeLists.txt"),
        get_component_cmakelists(),
    )
