version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # Hypotehsis is only used for testing and is updated quite often
      - dependency-name: hypothesis
