---
version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    ignore:
      # Hypotehsis is only used for testing and is updated quite often
      - dependency-name: hypothesis
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
