[build]
  publish = "public"
  command = "make netlify"
  environment = { HUGO_BASEURL = "https://esphome.io", HUGOxPARAMSxAPI_DOCS_URL = "https://api-docs.esphome.io", PYTHON_VERSION = "3.12", HUGO_VERSION = "0.147.8" }

[context.beta]
  environment = { HUGO_BASEURL = "https://beta.esphome.io", HUGOxPARAMSxAPI_DOCS_URL = "https://api-docs-beta.esphome.io" }

[context.next]
  environment = { HUGO_BASEURL = "https://next.esphome.io", HUGOxPARAMSxAPI_DOCS_URL = "https://api-docs-dev.esphome.io" }

[context.production]
  environment = { HUGO_BASEURL = "https://esphome.io", HUGOxPARAMSxAPI_DOCS_URL = "https://api-docs.esphome.io" }


# Caching HTML - 1 week
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Images, CSS, JS - 1 year, immutable. CSS and JS are fingerprinted
[[headers]]
  for = "/*.{png,jpg,jpeg,gif,webp,svg,css,js}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/_images/*"
to = "/images/:splat"
status = 301


[[redirects]]
  from = "/esphomeyaml/*"
  to = "/:splat"
  status = 301

[[redirects]]
  from = "/chat"
  to = "https://discord.gg/KhAMKrd"
  status = 301

# This redirect is for the api docs that have been moved.
# It is replaced by sed in the makefile when netlify is building the site.
[[redirects]]
  from = "/api/*"
  to = "{{HUGOxPARAMSxAPI_DOCS_URL}}/:splat"
  status = 301

# Webserver files
[[redirects]]
  from = "/_static/webserver-v1.*"
  to = "https://oi.esphome.io/v1/webserver-v1.:splat"
  status = 301

# Moved components

[[redirects]]
  from = "/components/sensor/sgp40.html"
  to = "/components/sensor/sgp4x.html"
  status = 301

[[redirects]]
  from = "/components/binary_sensor/xpt2046.html"
  to = "/components/touchscreen/xpt2046.html"
  status = 301

[[redirects]]
  from = "/devices/esp8266.html"
  to = "/components/esp8266.html"
  status = 301

[[redirects]]
  from = "/devices/esp32.html"
  to = "/components/esp32.html"
  status = 301


[[redirects]]
  from = "/changelog/2022.12.4.html"
  to = "/changelog/2022.12.0.html"
  status = 301

[[redirects]]
  from = "/components/display/ili9341.html"
  to = "/components/display/ili9xxx.html"
  status = 301

[[redirects]]
  from = "/components/ota.html"
  to = "/components/ota/esphome.html"
  status = 301

[[redirects]]
  from = "/components/ota_http_request*"
  to = "/components/ota/http_request.html"
  status = 301

[[redirects]]
  from = "/components/sensor/mmc5063*"
  to = "/components/sensor/mmc5603.html"
  status = 301

[[redirects]]
  from = "/components/sensor/kalman_combinator*"
  to = "/components/sensor/combination.html"
  status = 301

[[redirects]]
  from = "/components/display/inkplate6*"
  to = "/components/display/inkplate.html"
  status = 301


[[redirects]]
  from = "/guides/contributing*"
  to = "https://developers.esphome.io/contributing/code/"
  status = 301


[[redirects]]
  from = "/components/binary_sensor/custom*"
  to = "https://developers.esphome.io/blog/2025/02/19/about-the-removal-of-support-for-custom-components/"
  status = 301

[[redirects]]
  from = "/components/climate/custom*"
  to = "https://developers.esphome.io/blog/2025/02/19/about-the-removal-of-support-for-custom-components/"
  status = 301

[[redirects]]
  from = "/components/cover/custom*"
  to = "https://developers.esphome.io/blog/2025/02/19/about-the-removal-of-support-for-custom-components/"
  status = 301

[[redirects]]
  from = "/components/light/custom*"
  to = "https://developers.esphome.io/blog/2025/02/19/about-the-removal-of-support-for-custom-components/"
  status = 301

[[redirects]]
  from = "/components/output/custom*"
  to = "https://developers.esphome.io/blog/2025/02/19/about-the-removal-of-support-for-custom-components/"
  status = 301

[[redirects]]
  from = "/components/sensor/custom*"
  to = "https://developers.esphome.io/blog/2025/02/19/about-the-removal-of-support-for-custom-components/"
  status = 301

[[redirects]]
  from = "/components/switch/custom*"
  to = "https://developers.esphome.io/blog/2025/02/19/about-the-removal-of-support-for-custom-components/"
  status = 301

[[redirects]]
  from = "/components/text_sensor/custom*"
  to = "https://developers.esphome.io/blog/2025/02/19/about-the-removal-of-support-for-custom-components/"
  status = 301

[[redirects]]
  from = "/custom/custom_component*"
  to = "https://developers.esphome.io/blog/2025/02/19/about-the-removal-of-support-for-custom-components/"
  status = 301

[[redirects]]
  from = "/custom/i2c*"
  to = "https://developers.esphome.io/blog/2025/02/19/about-the-removal-of-support-for-custom-components/"
  status = 301

[[redirects]]
  from = "/custom/index*"
  to = "https://developers.esphome.io/blog/2025/02/19/about-the-removal-of-support-for-custom-components/"
  status = 301

[[redirects]]
  from = "/custom/spi*"
  to = "https://developers.esphome.io/blog/2025/02/19/about-the-removal-of-support-for-custom-components/"
  status = 301

[[redirects]]
  from = "/custom/uart*"
  to = "https://developers.esphome.io/blog/2025/02/19/about-the-removal-of-support-for-custom-components/"
  status = 301

[[redirects]]
  from = "/cookbook/brilliant-mirabella-genio-smart-plugs.html"
  to = "https://devices.esphome.io/devices/Mirabella-Genio-Wi-Fi-1-USB"
  status = 301

[[redirects]]
  from = "/cookbook/zemismart-rgbw-downlights.html"
  to = "https://devices.esphome.io/devices/Zemismart-LED-RGBWW-Downlight"
  status = 301

[[redirects]]
  from = "/cookbook/relay.html"
  to = "https://devices.esphome.io/devices/Generic-Relay"
  status = 301

[[redirects]]
  from = "/cookbook/pir.html"
  to = "https://devices.esphome.io/devices/Generic-PIR"
  status = 301

[[redirects]]
  from = "/cookbook/mirabella-genio-bulb.html"
  to = "https://devices.esphome.io/devices/Mirabella-Genio-Monochromatic-Bulbs"
  status = 301

[[redirects]]
  from = "/cookbook/air_gradient_diy_air_quality_sensor.html"
  to = "https://devices.esphome.io/devices/AirGradient-DIY"
  status = 301

[[redirects]]
  from = "/cookbook/ble_itag.html"
  to = "https://devices.esphome.io/devices/ble_itag"
  status = 301

[[redirects]]
  from = "/cookbook/bruh.html"
  to = "https://devices.esphome.io/devices/bruh"
  status = 301

[[redirects]]
  from = "/cookbook/esw01-eu.html"
  to = "https://devices.esphome.io/devices/Etekcity-Voltson-ESW01-EU"
  status = 301

[[redirects]]
  from = "/cookbook/geiger-counter.html"
  to = "https://devices.esphome.io/devices/geiger-counter"
  status = 301

[[redirects]]
  from = "/cookbook/h801.html"
  to = "https://devices.esphome.io/devices/H801-RGBW-LED-Controller"
  status = 301

[[redirects]]
  from = "/cookbook/iaq_board.html"
  to = "https://devices.esphome.io/devices/iaq_board"
  status = 301

[[redirects]]
  from = "/cookbook/ifan02.html"
  to = "https://devices.esphome.io/devices/Sonoff-iFan02"
  status = 301

[[redirects]]
  from = "/cookbook/ilonda-wifi-smart-fish-feeder.html"
  to = "https://devices.esphome.io/devices/ilonda-wifi-smart-fish-feeder"
  status = 301

[[redirects]]
  from = "/cookbook/iwoole_rgbw_table_lamp.html"
  to = "https://devices.esphome.io/devices/iwoole_rgbw_table_lamp"
  status = 301

[[redirects]]
  from = "/cookbook/teckin_sb50.html"
  to = "https://devices.esphome.io/devices/Teckin-SB50_rgbww"
  status = 301

[[redirects]]
  from = "/cookbook/temt6000.html"
  to = "https://devices.esphome.io/devices/temt6000"
  status = 301

[[redirects]]
  from = "/cookbook/tracer-an.html"
  to = "https://devices.esphome.io/devices/epever_mptt_tracer_an"
  status = 301

[[redirects]]
  from = "/cookbook/tuya_rgbw.html"
  to = "https://devices.esphome.io/devices/tuya_rgbw"
  status = 301

[[redirects]]
  from = "/cookbook/uart_text_sensor.html"
  to = "/cookbook/lambda_magic.html#custom-uart-text-sensor"
  status = 301

[[redirects]]
  from = "/cookbook/endstop-cover.html"
  to = "/components/cover/endstop.html"
  status = 301

[[redirects]]
  from = "/cookbook/sonoff-light-switch.html"
  to = "https://devices.esphome.io/devices/Sonoff-Dual-DIY-light"
  status = 301

[[redirects]]
  from = "/cookbook/sonoff-basic-light-switch.html"
  to = "https://devices.esphome.io/devices/Sonoff-Basic-DIY-light"
  status = 301

[[redirects]]
  from = "/cookbook/sonoff-dual-light-switch.html"
  to = "https://devices.esphome.io/devices/Sonoff-Dual-DIY-light"
  status = 301

[[redirects]]
  from = "/cookbook/sonoff-t1-3.html"
  to = "https://devices.esphome.io/devices/Sonoff-T1-T2-T3"
  status = 301

[[redirects]]
  from = "/cookbook/dual-r2-cover.html"
  to = "/cookbook/lambda_magic.html#one-button-cover-control"
  status = 301

[[redirects]]
  from = "/ready-made/projects"
  to = "/projects/"
  status = 301

[[redirects]]
  from = "/components/images"
  to = "/components/image"
  status = 301

[[redirects]]
  from = "/components/display/qspi_amoled.html"
  to = "/components/display/mipi_spi.html"
  status = 301
