esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

uart:
  rx_pin: GPIO10
  parity: EVEN
  baud_rate: 9600

esphome:
  name: pannypm

logger:
  level: VERBOSE

sensor:
  - platform: gcja5
    pm_1_0:
      name: "Particulate Matter <1.0µm Concentration"
    pm_10_0:
      name: "Particulate Matter <10.0µm Concentration"
    pm_2_5:
      name: "Particulate Matter <2.5µm Concentration"
