CONF_AUTO_WAKE = "auto_wake"
CONF_CLUSTER_ID = "cluster_id"
CONF_DOP_IDX = "dop_idx"
CONF_LD6002B_ID = "ld6002b_id"
CONF_MAX_DATA_LEN = "max_data_len"
CONF_POINT_COUNT = "point_count"
CONF_WAKEUP_PULSE = "wakeup_pulse"
CONF_Z = "z"

KEY_TARGET_COUNT = "target_count"
