"""Generate clang-tidy idedata via the native ESP-IDF toolchain.

Produces idedata for clang-tidy **without an ESPHome YAML config**. Instead of
running codegen on a config, it generates a minimal ESP-IDF CMake project:

* the managed-component dependencies come from ESPHome's own
  ``idf_component.yml`` (arduinojson, lvgl, mdns, ...);
* the PlatformIO ``lib_deps`` (qr-code, mlx90393, ...) are converted to local
  IDF components via the ESPHome PlatformIO->IDF converter;
* the ``main`` component ``REQUIRES`` every target-available builtin IDF
  component, so their public include dirs land on the translation unit;
* the repo ``sdkconfig.defaults`` enables sdkconfig-gated components (bt, ...).

then runs ``idf.py reconfigure`` (configure only, no compile) and reads the
resulting ``build/compile_commands.json``. The IDF version is the esp32
component's recommended version.

``ESPHOME_IDF_COMPILE_COMMANDS`` may point at an existing build's
``compile_commands.json`` to skip generation (fast iteration).
"""

import os
from pathlib import Path

TIDY_PROJECT_NAME = "esphome_tidy"

# A do-nothing C++ app: just enough for IDF to configure a valid project. It's
# C++ (not C) so the compile command uses the C++ compiler and flags, matching
# how clang-tidy analyzes ESPHome's C++ sources.
_TIDY_MAIN_CPP = 'extern "C" void app_main() {}\n'


def _platform_defines(variant: str) -> tuple[str, ...]:
    """Return the platform defines a real ESPHome build adds via cg.add_define.

    defines.h only *consumes* these (it provides the feature USE_* flags and the
    ESPHOME_LOG_LEVEL default). Without them, esphome/core/hal.h errors with
    "not implemented for this platform". Mirrors the esp32-idf-tidy -D set.
    ``variant`` is the upper-case esp32 variant (ESP32, ESP32S3, ...).
    """
    return (
        "USE_ESP32",
        "USE_ESP_IDF",
        "USE_ESP32_FRAMEWORK_ESP_IDF",
        f"USE_ESP32_VARIANT_{variant}",
    )


_TOP_CMAKELISTS = """\
# Auto-generated by ESPHome (clang-tidy idedata project)
cmake_minimum_required(VERSION 3.16)
set(IDF_TARGET {idf_target})
include($ENV{{IDF_PATH}}/tools/cmake/project.cmake)
{compile_options}
project({name})
"""

_MAIN_CMAKELISTS = """\
# Auto-generated by ESPHome (clang-tidy idedata project)
idf_component_register(
    SRCS "tidy.cpp"
    REQUIRES {requires}
)
"""


def _recommended_idf_version() -> str:
    from esphome.components.esp32 import ESP_IDF_FRAMEWORK_VERSION_LOOKUP

    return str(ESP_IDF_FRAMEWORK_VERSION_LOOKUP["recommended"])


def _setup_core(work_dir: Path, version: str, variant: str) -> None:
    """Point CORE at the tidy project + IDF version, without any YAML config."""
    from esphome.components.esp32.const import KEY_ESP32, KEY_IDF_VERSION, KEY_VARIANT
    import esphome.config_validation as cv
    from esphome.const import KEY_CORE, KEY_TARGET_FRAMEWORK, KEY_TARGET_PLATFORM
    from esphome.core import CORE

    CORE.name = TIDY_PROJECT_NAME
    # config_path's parent is the data dir root: the IDF install lives at
    # ``<parent>/.esphome/idf`` -- keep it beside (not inside) the per-run
    # project dir so clearing the project doesn't force an IDF re-download.
    CORE.config_path = work_dir.parent / "tidy.yaml"
    CORE.build_path = work_dir
    esp32 = CORE.data.setdefault(KEY_ESP32, {})
    esp32[KEY_IDF_VERSION] = cv.Version.parse(version)
    esp32[KEY_VARIANT] = variant
    # The PlatformIO-library -> IDF-component converter reads the target.
    CORE.data.setdefault(KEY_CORE, {})[KEY_TARGET_PLATFORM] = "esp32"
    CORE.data[KEY_CORE][KEY_TARGET_FRAMEWORK] = "espidf"


# Special IDF "components" that are tools/subprojects, not requirable by an app
# (they provide no public includes and break requirement resolution), plus our
# own ``main``.
_NON_REQUIRABLE_COMPONENTS = frozenset(
    {"bootloader", "esptool_py", "partition_table", "main"}
)


def _parse_lib_deps(platformio_ini: Path):
    """Parse the esp32-idf ``lib_deps`` from platformio.ini into Library specs.

    These are the PlatformIO libraries ESPHome components pull in via
    ``cg.add_library`` (qr-code, mlx90393, noise-c, ...). The esp32-idf build
    aggregates ``[common] lib_deps`` (which expands ``lib_deps_base``) plus the
    ``[common:esp32-idf]`` additions; we read those sections directly and skip
    the ``${...}`` cross-references and non-library entries.
    """
    import configparser

    from esphome.core import Library

    parser = configparser.ConfigParser(interpolation=None, strict=False)
    parser.read(platformio_ini)

    tokens: list[str] = []
    for section, key in (
        ("common", "lib_deps_base"),
        ("common", "lib_deps"),
        ("common:esp32-idf", "lib_deps"),
    ):
        if parser.has_option(section, key):
            tokens += parser.get(section, key).splitlines()

    libs: list[Library] = []
    seen: set[str] = set()
    for token in tokens:
        token = token.split(";", 1)[0].strip()  # drop trailing ; comment
        # Skip blanks, ${...} cross-refs, and +<...> source filters.
        if not token or token.startswith(("${", "+<")) or token in seen:
            continue
        seen.add(token)
        if "://" in token or ".git" in token:
            libs.append(Library(token, None, token))  # git repository (with #ref)
        elif "@" in token:
            name, _, version = token.partition("@")
            libs.append(Library(name, version))
        else:
            libs.append(Library(token, None))
    return libs


def _convert_pio_libs(platformio_ini: Path) -> dict[str, dict[str, str]]:
    """Convert each PlatformIO lib to an IDF component; return manifest deps.

    Returns a mapping suitable for an ``idf_component.yml`` ``dependencies``
    block (``{name: {"override_path": <converted component dir>}}``), reusing
    ESPHome's own PlatformIO->IDF converter (registry/git resolution, no pio).
    """
    from esphome.espidf.component import generate_idf_component

    deps: dict[str, dict[str, str]] = {}
    for library in _parse_lib_deps(platformio_ini):
        name, _version, path = generate_idf_component(library)
        deps[name] = {"override_path": str(path)}
    return deps


def _write_tidy_project(
    work_dir: Path,
    requires: list[str],
    extra_deps: dict[str, dict[str, str]],
    idf_target: str,
    variant: str,
) -> None:
    """Generate the minimal IDF CMake project (top + main + idf_component.yml)."""
    main_dir = work_dir / "main"
    main_dir.mkdir(parents=True, exist_ok=True)

    compile_options = "\n".join(
        f'idf_build_set_property(COMPILE_OPTIONS "-D{define}" APPEND)'
        for define in _platform_defines(variant)
    )
    (work_dir / "CMakeLists.txt").write_text(
        _TOP_CMAKELISTS.format(
            name=TIDY_PROJECT_NAME,
            compile_options=compile_options,
            idf_target=idf_target,
        ),
        encoding="utf-8",
    )
    (main_dir / "CMakeLists.txt").write_text(
        _MAIN_CMAKELISTS.format(requires=" ".join(requires)), encoding="utf-8"
    )
    (main_dir / "tidy.cpp").write_text(_TIDY_MAIN_CPP, encoding="utf-8")

    # Managed components: ESPHome's own manifest (arduinojson, lvgl, mdns, ...),
    # plus the converted PlatformIO libs as local (override_path) deps. Placing
    # it in main/ makes every dep a requirement of the main component, so their
    # public includes land on the tidy translation unit.
    import yaml

    esphome_dir = Path(__file__).resolve().parent.parent  # esphome/espidf -> esphome
    manifest = yaml.safe_load(
        (esphome_dir / "idf_component.yml").read_text(encoding="utf-8")
    )
    manifest.setdefault("dependencies", {}).update(extra_deps)
    (main_dir / "idf_component.yml").write_text(
        yaml.safe_dump(manifest, sort_keys=False), encoding="utf-8"
    )

    # ESPHome's static-analysis sdkconfig (repo root): enables the flags any
    # component sets (e.g. CONFIG_BT_ENABLED) so sdkconfig-gated IDF components
    # register and expose their includes. IDF reads ``sdkconfig.defaults`` from
    # the project root.
    (work_dir / "sdkconfig.defaults").write_text(
        (esphome_dir.parent / "sdkconfig.defaults").read_text(encoding="utf-8"),
        encoding="utf-8",
    )


def _generate_compile_commands(
    work_dir: Path, version: str, platformio_ini: Path, idf_target: str, variant: str
) -> Path:
    """Generate the tidy project and run ``idf.py reconfigure`` (no build).

    Two-phase, like a real ESPHome build: a first configure with no builtin
    requires discovers which components actually register for the target (e.g.
    ``esp_tee`` only registers on c5/c6/h2), then a second configure requires
    that discovered set so their public includes reach the tidy TU.
    """
    import logging

    from esphome.build_gen.espidf import get_available_components
    from esphome.espidf import toolchain

    # Surface ESPHome's INFO logs (ESP-IDF framework download/extract/install,
    # git-library clones) -- they go through logging, which the clang-tidy
    # script otherwise leaves at WARNING so the first-run downloads look silent.
    logging.basicConfig(level=logging.INFO, format="%(message)s")

    _setup_core(work_dir, version, variant)

    # PlatformIO libs -> local IDF components, added to the manifest as deps.
    extra_deps = _convert_pio_libs(platformio_ini)

    # Phase 1: discover the components available for this target.
    _write_tidy_project(work_dir, [], extra_deps, idf_target, variant)
    if toolchain.run_reconfigure() != 0:
        raise RuntimeError("idf.py reconfigure (discovery) failed")

    requires = sorted(
        set(get_available_components() or []) - _NON_REQUIRABLE_COMPONENTS
    )

    # Phase 2: require every available builtin component.
    _write_tidy_project(work_dir, requires, extra_deps, idf_target, variant)
    if toolchain.run_reconfigure() != 0:
        raise RuntimeError("idf.py reconfigure failed")

    return work_dir / "build" / "compile_commands.json"


def _idedata_from_tidy_project(compile_commands: Path) -> dict:
    """Assemble idedata from the single tidy translation unit.

    Unlike a real ESPHome build (many ``/src/esphome/`` TUs unioned), the tidy
    project has one TU (``main/tidy.cpp``) that -- by requiring every component --
    already carries the full include set, so we parse it directly.
    """
    import json

    from esphome.espidf.idedata import _get_toolchain_includes, _parse_entry

    entries = json.loads(Path(compile_commands).read_text(encoding="utf-8"))
    entry = next(e for e in entries if e["file"].endswith("tidy.cpp"))
    cxx_path, defines, includes, cxx_flags = _parse_entry(entry)

    return {
        "cxx_path": cxx_path,
        "cxx_flags": cxx_flags,
        "defines": defines,
        "includes": {
            "build": includes,
            "toolchain": _get_toolchain_includes(cxx_path),
        },
    }


def load_idedata(environment: str, temp_folder: str, platformio_ini: str) -> dict:
    if explicit := os.environ.get("ESPHOME_IDF_COMPILE_COMMANDS"):
        compile_commands = Path(explicit)
    else:
        # The tidy env is ``<target>-idf-tidy`` (esp32, esp32s3, esp32c6, ...);
        # the IDF target is that prefix and the esp32 variant its upper-case.
        idf_target = environment.split("-", 1)[0]
        variant = idf_target.upper()
        work_dir = Path(temp_folder) / f"idf-tidy-{idf_target}"
        compile_commands = _generate_compile_commands(
            work_dir,
            _recommended_idf_version(),
            Path(platformio_ini),
            idf_target,
            variant,
        )

    if not compile_commands.is_file():
        raise RuntimeError(f"compile_commands.json not found: {compile_commands}")
    return _idedata_from_tidy_project(compile_commands)
