sensor:
  - platform: toptronic
    name: TKO1 collector temperature
    device_type: SOL
    function_group: 22
    function_number: 0
    datapoint: 14
    id: SOL_22_0_14
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
  - platform: toptronic
    name: TKO2 collector temperature
    device_type: SOL
    function_group: 22
    function_number: 1
    datapoint: 14
    id: SOL_22_1_14
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
  - platform: toptronic
    name: Total yield collector (2)
    device_type: SOL
    function_group: 22
    function_number: 1
    datapoint: 2034
    id: SOL_22_1_2034
    type: S32
    unit_of_measurement: kWh
    icon: mdi:flash
    device_class: energy
    state_class: measurement
  - platform: toptronic
    name: Current collector output (2)
    device_type: SOL
    function_group: 22
    function_number: 1
    datapoint: 2030
    id: SOL_22_1_2030
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: kW
    icon: mdi:lightning-bolt
    device_class: power
    state_class: measurement
  - platform: toptronic
    name: Operating hours pump Solar (1)
    device_type: SOL
    function_group: 22
    function_number: 0
    datapoint: 2032
    id: SOL_22_0_2032
    type: U16
  - platform: toptronic
    name: Operating hours pump Solar (2)
    device_type: SOL
    function_group: 22
    function_number: 1
    datapoint: 2032
    id: SOL_22_1_2032
    type: U16
  - platform: toptronic
    name: Total yield collector (1)
    device_type: SOL
    function_group: 22
    function_number: 0
    datapoint: 2034
    id: SOL_22_0_2034
    type: S32
    unit_of_measurement: kWh
    icon: mdi:flash
    device_class: energy
    state_class: measurement
  - platform: toptronic
    name: Current collector output (1)
    device_type: SOL
    function_group: 22
    function_number: 0
    datapoint: 2030
    id: SOL_22_0_2030
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: kW
    icon: mdi:lightning-bolt
    device_class: power
    state_class: measurement
  - platform: toptronic
    name: Solar controller status (1)
    device_type: SOL
    function_group: 22
    function_number: 0
    datapoint: 2056
    id: SOL_22_0_2056
    type: U8
  - platform: toptronic
    name: Solar controller status (2)
    device_type: SOL
    function_group: 22
    function_number: 1
    datapoint: 2056
    id: SOL_22_1_2056
    type: U8
  - platform: toptronic
    name: TU storage tank bottom temp. (1)
    device_type: SOL
    function_group: 23
    function_number: 0
    datapoint: 16
    id: SOL_23_0_16
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
  - platform: toptronic
    name: TO storage tank top temp. (1)
    device_type: SOL
    function_group: 23
    function_number: 0
    datapoint: 15
    id: SOL_23_0_15
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
  - platform: toptronic
    name: TU storage tank bottom temp. (2)
    device_type: SOL
    function_group: 23
    function_number: 1
    datapoint: 16
    id: SOL_23_1_16
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
  - platform: toptronic
    name: TO storage tank top temp. (2)
    device_type: SOL
    function_group: 23
    function_number: 1
    datapoint: 15
    id: SOL_23_1_15
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
  - platform: toptronic
    name: TU storage tank bottom temp. (3)
    device_type: SOL
    function_group: 23
    function_number: 2
    datapoint: 16
    id: SOL_23_2_16
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
  - platform: toptronic
    name: TO storage tank top temp. (3)
    device_type: SOL
    function_group: 23
    function_number: 2
    datapoint: 15
    id: SOL_23_2_15
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
  - platform: toptronic
    name: TU storage tank bottom temp. (4)
    device_type: SOL
    function_group: 23
    function_number: 3
    datapoint: 16
    id: SOL_23_3_16
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
  - platform: toptronic
    name: TO storage tank top temp. (4)
    device_type: SOL
    function_group: 23
    function_number: 3
    datapoint: 15
    id: SOL_23_3_15
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
  - platform: toptronic
    name: Vset volume flow solar circuit (1)
    device_type: SOL
    function_group: 22
    function_number: 0
    datapoint: 62
    id: SOL_22_0_62
    type: S16
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    unit_of_measurement: l/min
    icon: mdi:water-outline
    device_class: volume_flow_rate
    state_class: measurement
  - platform: toptronic
    name: TKV collector supply temp. (1)
    device_type: SOL
    function_group: 22
    function_number: 0
    datapoint: 60
    id: SOL_22_0_60
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
  - platform: toptronic
    name: TKR collector return temp. (1)
    device_type: SOL
    function_group: 22
    function_number: 0
    datapoint: 61
    id: SOL_22_0_61
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
  - platform: toptronic
    name: Current speed pump Solar (1)
    device_type: SOL
    function_group: 22
    function_number: 0
    datapoint: 1050
    id: SOL_22_0_1050
    type: U8
    unit_of_measurement: '%'
    icon: mdi:percent
    device_class: power_factor
    state_class: measurement
  - platform: toptronic
    name: Vset volume flow solar circuit (2)
    device_type: SOL
    function_group: 22
    function_number: 1
    datapoint: 62
    id: SOL_22_1_62
    type: S16
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    unit_of_measurement: l/min
    icon: mdi:water-outline
    device_class: volume_flow_rate
    state_class: measurement
  - platform: toptronic
    name: TKV collector supply temp. (2)
    device_type: SOL
    function_group: 22
    function_number: 1
    datapoint: 60
    id: SOL_22_1_60
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
  - platform: toptronic
    name: TKR collector return temp. (2)
    device_type: SOL
    function_group: 22
    function_number: 1
    datapoint: 61
    id: SOL_22_1_61
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
  - platform: toptronic
    name: Current speed pump Solar (2)
    device_type: SOL
    function_group: 22
    function_number: 1
    datapoint: 1050
    id: SOL_22_1_1050
    type: U8
    unit_of_measurement: '%'
    icon: mdi:percent
    device_class: power_factor
    state_class: measurement
  - platform: toptronic
    name: Priority storage tank (1)
    device_type: SOL
    function_group: 23
    function_number: 0
    datapoint: 8056
    id: SOL_23_0_8056
    type: U8
    internal: true
  - platform: toptronic
    name: Priority storage tank (2)
    device_type: SOL
    function_group: 23
    function_number: 1
    datapoint: 8056
    id: SOL_23_1_8056
    type: U8
    internal: true
  - platform: toptronic
    name: Priority storage tank (3)
    device_type: SOL
    function_group: 23
    function_number: 2
    datapoint: 8056
    id: SOL_23_2_8056
    type: U8
    internal: true
  - platform: toptronic
    name: Priority storage tank (4)
    device_type: SOL
    function_group: 23
    function_number: 3
    datapoint: 8056
    id: SOL_23_3_8056
    type: U8
    internal: true
  - platform: toptronic
    name: Storage tank max. temp. (1)
    device_type: SOL
    function_group: 23
    function_number: 0
    datapoint: 8059
    id: SOL_23_0_8059
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
    internal: true
  - platform: toptronic
    name: Storage tank max. temp. (2)
    device_type: SOL
    function_group: 23
    function_number: 1
    datapoint: 8059
    id: SOL_23_1_8059
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
    internal: true
  - platform: toptronic
    name: Storage tank max. temp. (3)
    device_type: SOL
    function_group: 23
    function_number: 2
    datapoint: 8059
    id: SOL_23_2_8059
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
    internal: true
  - platform: toptronic
    name: Storage tank max. temp. (4)
    device_type: SOL
    function_group: 23
    function_number: 3
    datapoint: 8059
    id: SOL_23_3_8059
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
    internal: true
  - platform: toptronic
    name: Storage tank protection temp. (1)
    device_type: SOL
    function_group: 23
    function_number: 0
    datapoint: 8060
    id: SOL_23_0_8060
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
    internal: true
  - platform: toptronic
    name: Storage tank protection temp. (2)
    device_type: SOL
    function_group: 23
    function_number: 1
    datapoint: 8060
    id: SOL_23_1_8060
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
    internal: true
  - platform: toptronic
    name: Storage tank protection temp. (3)
    device_type: SOL
    function_group: 23
    function_number: 2
    datapoint: 8060
    id: SOL_23_2_8060
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
    internal: true
  - platform: toptronic
    name: Storage tank protection temp. (4)
    device_type: SOL
    function_group: 23
    function_number: 3
    datapoint: 8060
    id: SOL_23_3_8060
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
    internal: true
  - platform: toptronic
    name: Storage tank set temperature (1)
    device_type: SOL
    function_group: 23
    function_number: 0
    datapoint: 8062
    id: SOL_23_0_8062
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
    internal: true
  - platform: toptronic
    name: Storage tank set temperature (2)
    device_type: SOL
    function_group: 23
    function_number: 1
    datapoint: 8062
    id: SOL_23_1_8062
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
    internal: true
  - platform: toptronic
    name: Storage tank set temperature (3)
    device_type: SOL
    function_group: 23
    function_number: 2
    datapoint: 8062
    id: SOL_23_2_8062
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
    internal: true
  - platform: toptronic
    name: Storage tank set temperature (4)
    device_type: SOL
    function_group: 23
    function_number: 3
    datapoint: 8062
    id: SOL_23_3_8062
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
    internal: true
  - platform: toptronic
    name: Current set collector temp. (1)
    device_type: SOL
    function_group: 22
    function_number: 0
    datapoint: 1014
    id: SOL_22_0_1014
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
  - platform: toptronic
    name: Current set collector temp. (2)
    device_type: SOL
    function_group: 22
    function_number: 1
    datapoint: 1014
    id: SOL_22_1_1014
    type: S16
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    unit_of_measurement: "\xB0C"
    icon: mdi:temperature-celsius
    device_class: temperature
    state_class: measurement
  - platform: toptronic
    name: UVP switching valve current state (1)
    device_type: SOL
    function_group: 23
    function_number: 0
    datapoint: 1052
    id: SOL_23_0_1052
    type: U8
  - platform: toptronic
    name: UVP switching valve current state (2)
    device_type: SOL
    function_group: 23
    function_number: 1
    datapoint: 1052
    id: SOL_23_1_1052
    type: U8
  - platform: toptronic
    name: UVP switching valve current state (3)
    device_type: SOL
    function_group: 23
    function_number: 2
    datapoint: 1052
    id: SOL_23_2_1052
    type: U8
  - platform: toptronic
    name: Partial yield collector (1)
    device_type: SOL
    function_group: 22
    function_number: 0
    datapoint: 2031
    id: SOL_22_0_2031
    type: U16
    unit_of_measurement: kWh
    icon: mdi:flash
    device_class: energy
    state_class: measurement
  - platform: toptronic
    name: Partial yield collector (2)
    device_type: SOL
    function_group: 22
    function_number: 1
    datapoint: 2031
    id: SOL_22_1_2031
    type: U16
    unit_of_measurement: kWh
    icon: mdi:flash
    device_class: energy
    state_class: measurement
