import esphome.codegen as cg

ha_standard_devices = cg.esphome_ns.enum("esp_zb_ha_standard_devices_t")
DEVICE_ID = {
    "SIMPLE_SENSOR": ha_standard_devices.ESP_ZB_HA_SIMPLE_SENSOR_DEVICE_ID,
    0x000C: ha_standard_devices.ESP_ZB_HA_SIMPLE_SENSOR_DEVICE_ID,
    "TEST": ha_standard_devices.ESP_ZB_HA_TEST_DEVICE_ID,
    0xFFF0: ha_standard_devices.ESP_ZB_HA_TEST_DEVICE_ID,
    "CUSTOM_ATTR": ha_standard_devices.ESP_ZB_HA_CUSTOM_ATTR_DEVICE_ID,
    0xFFF2: ha_standard_devices.ESP_ZB_HA_CUSTOM_ATTR_DEVICE_ID,
}
cluster_id = cg.esphome_ns.enum("esp_zb_zcl_cluster_id_t")
CLUSTER_ID = {
    "BASIC": cluster_id.ESP_ZB_ZCL_CLUSTER_ID_BASIC,
    0x0000: cluster_id.ESP_ZB_ZCL_CLUSTER_ID_BASIC,
    "IDENTIFY": cluster_id.ESP_ZB_ZCL_CLUSTER_ID_IDENTIFY,
    0x0003: cluster_id.ESP_ZB_ZCL_CLUSTER_ID_IDENTIFY,
    "GROUPS": cluster_id.ESP_ZB_ZCL_CLUSTER_ID_GROUPS,
    0x0004: cluster_id.ESP_ZB_ZCL_CLUSTER_ID_GROUPS,
    "SCENES": cluster_id.ESP_ZB_ZCL_CLUSTER_ID_SCENES,
    0x0005: cluster_id.ESP_ZB_ZCL_CLUSTER_ID_SCENES,
    "BINARY_INPUT": cluster_id.ESP_ZB_ZCL_CLUSTER_ID_BINARY_INPUT,
    0x000F: cluster_id.ESP_ZB_ZCL_CLUSTER_ID_BINARY_INPUT,
}
cluster_role = cg.esphome_ns.enum("esp_zb_zcl_cluster_role_t")
CLUSTER_ROLE = {
    "SERVER": cluster_role.ESP_ZB_ZCL_CLUSTER_SERVER_ROLE,
    "CLIENT": cluster_role.ESP_ZB_ZCL_CLUSTER_CLIENT_ROLE,
}
attr_type = cg.esphome_ns.enum("esp_zb_zcl_attr_type_t")
ATTR_TYPE = {
    "NULL": attr_type.ESP_ZB_ZCL_ATTR_TYPE_NULL,
    "8BIT": attr_type.ESP_ZB_ZCL_ATTR_TYPE_8BIT,
    "16BIT": attr_type.ESP_ZB_ZCL_ATTR_TYPE_16BIT,
    "24BIT": attr_type.ESP_ZB_ZCL_ATTR_TYPE_24BIT,
    "32BIT": attr_type.ESP_ZB_ZCL_ATTR_TYPE_32BIT,
    "40BIT": attr_type.ESP_ZB_ZCL_ATTR_TYPE_40BIT,
    "48BIT": attr_type.ESP_ZB_ZCL_ATTR_TYPE_48BIT,
    "56BIT": attr_type.ESP_ZB_ZCL_ATTR_TYPE_56BIT,
    "64BIT": attr_type.ESP_ZB_ZCL_ATTR_TYPE_64BIT,
    "BOOL": attr_type.ESP_ZB_ZCL_ATTR_TYPE_BOOL,
    "8BITMAP": attr_type.ESP_ZB_ZCL_ATTR_TYPE_8BITMAP,
    "16BITMAP": attr_type.ESP_ZB_ZCL_ATTR_TYPE_16BITMAP,
    "24BITMAP": attr_type.ESP_ZB_ZCL_ATTR_TYPE_24BITMAP,
    "32BITMAP": attr_type.ESP_ZB_ZCL_ATTR_TYPE_32BITMAP,
    "40BITMAP": attr_type.ESP_ZB_ZCL_ATTR_TYPE_40BITMAP,
    "48BITMAP": attr_type.ESP_ZB_ZCL_ATTR_TYPE_48BITMAP,
    "56BITMAP": attr_type.ESP_ZB_ZCL_ATTR_TYPE_56BITMAP,
    "64BITMAP": attr_type.ESP_ZB_ZCL_ATTR_TYPE_64BITMAP,
    "U8": attr_type.ESP_ZB_ZCL_ATTR_TYPE_U8,
    "U16": attr_type.ESP_ZB_ZCL_ATTR_TYPE_U16,
    "U24": attr_type.ESP_ZB_ZCL_ATTR_TYPE_U24,
    "U32": attr_type.ESP_ZB_ZCL_ATTR_TYPE_U32,
    "U40": attr_type.ESP_ZB_ZCL_ATTR_TYPE_U40,
    "U48": attr_type.ESP_ZB_ZCL_ATTR_TYPE_U48,
    "U56": attr_type.ESP_ZB_ZCL_ATTR_TYPE_U56,
    "U64": attr_type.ESP_ZB_ZCL_ATTR_TYPE_U64,
    "S8": attr_type.ESP_ZB_ZCL_ATTR_TYPE_S8,
    "S16": attr_type.ESP_ZB_ZCL_ATTR_TYPE_S16,
    "S24": attr_type.ESP_ZB_ZCL_ATTR_TYPE_S24,
    "S32": attr_type.ESP_ZB_ZCL_ATTR_TYPE_S32,
    "S40": attr_type.ESP_ZB_ZCL_ATTR_TYPE_S40,
    "S48": attr_type.ESP_ZB_ZCL_ATTR_TYPE_S48,
    "S56": attr_type.ESP_ZB_ZCL_ATTR_TYPE_S56,
    "S64": attr_type.ESP_ZB_ZCL_ATTR_TYPE_S64,
    "8BIT_ENUM": attr_type.ESP_ZB_ZCL_ATTR_TYPE_8BIT_ENUM,
    "16BIT_ENUM": attr_type.ESP_ZB_ZCL_ATTR_TYPE_16BIT_ENUM,
    "SEMI": attr_type.ESP_ZB_ZCL_ATTR_TYPE_SEMI,
    "SINGLE": attr_type.ESP_ZB_ZCL_ATTR_TYPE_SINGLE,
    "DOUBLE": attr_type.ESP_ZB_ZCL_ATTR_TYPE_DOUBLE,
    "OCTET_STRING": attr_type.ESP_ZB_ZCL_ATTR_TYPE_OCTET_STRING,
    "CHAR_STRING": attr_type.ESP_ZB_ZCL_ATTR_TYPE_CHAR_STRING,
    "LONG_OCTET_STRING": attr_type.ESP_ZB_ZCL_ATTR_TYPE_LONG_OCTET_STRING,
    "LONG_CHAR_STRING": attr_type.ESP_ZB_ZCL_ATTR_TYPE_LONG_CHAR_STRING,
    "ARRAY": attr_type.ESP_ZB_ZCL_ATTR_TYPE_ARRAY,
    "16BIT_ARRAY": attr_type.ESP_ZB_ZCL_ATTR_TYPE_16BIT_ARRAY,
    "32BIT_ARRAY": attr_type.ESP_ZB_ZCL_ATTR_TYPE_32BIT_ARRAY,
    "STRUCTURE": attr_type.ESP_ZB_ZCL_ATTR_TYPE_STRUCTURE,
    "SET": attr_type.ESP_ZB_ZCL_ATTR_TYPE_SET,
    "BAG": attr_type.ESP_ZB_ZCL_ATTR_TYPE_BAG,
    "TIME_OF_DAY": attr_type.ESP_ZB_ZCL_ATTR_TYPE_TIME_OF_DAY,
    "DATE": attr_type.ESP_ZB_ZCL_ATTR_TYPE_DATE,
    "UTC_TIME": attr_type.ESP_ZB_ZCL_ATTR_TYPE_UTC_TIME,
    "CLUSTER_ID": attr_type.ESP_ZB_ZCL_ATTR_TYPE_CLUSTER_ID,
    "ATTRIBUTE_ID": attr_type.ESP_ZB_ZCL_ATTR_TYPE_ATTRIBUTE_ID,
    "BACNET_OID": attr_type.ESP_ZB_ZCL_ATTR_TYPE_BACNET_OID,
    "IEEE_ADDR": attr_type.ESP_ZB_ZCL_ATTR_TYPE_IEEE_ADDR,
    "128_BIT_KEY": attr_type.ESP_ZB_ZCL_ATTR_TYPE_128_BIT_KEY,
    "INVALID": attr_type.ESP_ZB_ZCL_ATTR_TYPE_INVALID,
}
ATTR_ACCESS = {
    "READ_ONLY": 1,
    "WRITE_ONLY": 2,
    "READ_WRITE": 3,
}
