# Auto-generated file. Do not edit.

BOARDS = {
    "96b_nitrogen": {
        "name": "Nitrogen",
        "mcu": "nrf52832",
        "vendor": "96boards",
        "external_flash": None,
        "bootloader": None,
    },
    "acn52832": {
        "name": "acn52832",
        "mcu": "nrf52832",
        "vendor": "aconno",
        "external_flash": None,
        "bootloader": None,
    },
    "adafruit_feather_nrf52840": {
        "name": "Feather nRF52840 (Express, Sense)",
        "mcu": "nrf52840",
        "vendor": "adafruit",
        "external_flash": {
            "label": "gd25q16",
            "size": 0x1000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": None,
    },
    "adafruit_itsybitsy": {
        "name": "ItsyBitsy nRF52840",
        "mcu": "nrf52840",
        "vendor": "adafruit",
        "external_flash": {
            "label": "gd25q16",
            "size": 0x1000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": {
            "type": "adafruit_nrf52_sd140_v6",
            "partitions": [
                {"name": "softdevice", "address": 0x0, "size": 0x26000},
                {"name": "adafruit_bootloader", "address": 0xF4000, "size": 0xC000},
            ],
        },
    },
    "arduino_nano_33_ble": {
        "name": "Arduino Nano 33 BLE (Sense)",
        "mcu": "nrf52840",
        "vendor": "arduino",
        "external_flash": None,
        "bootloader": {
            "type": "sam-ba",
            "partitions": [{"name": "sam-ba", "address": 0x0, "size": 0x10000}],
        },
    },
    "arduino_nicla_sense_me": {
        "name": "Arduino Nicla Sense ME",
        "mcu": "nrf52832",
        "vendor": "arduino",
        "external_flash": {
            "label": "mx25r1635f",
            "size": 0x1000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": {
            "type": "sam-ba",
            "partitions": [{"name": "sam-ba", "address": 0x0, "size": 0x10000}],
        },
    },
    "bbc_microbit_v2": {
        "name": "micro:bit V2",
        "mcu": "nrf52833",
        "vendor": "bbc",
        "external_flash": None,
        "bootloader": None,
    },
    "bl5340_dvk": {
        "name": "BL5340 DVK",
        "mcu": "nrf5340",
        "vendor": "ezurio",
        "external_flash": {
            "label": "mx25r64",
            "size": 0x4000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": None,
    },
    "bl652_dvk": {
        "name": "BL652 DVK",
        "mcu": "nrf52832",
        "vendor": "ezurio",
        "external_flash": None,
        "bootloader": None,
    },
    "bl653_dvk": {
        "name": "BL653 DVK",
        "mcu": "nrf52833",
        "vendor": "ezurio",
        "external_flash": None,
        "bootloader": None,
    },
    "bl654_dvk": {
        "name": "BL654 DVK",
        "mcu": "nrf52840",
        "vendor": "ezurio",
        "external_flash": None,
        "bootloader": None,
    },
    "bl654_sensor_board": {
        "name": "BL654 Sensor Board",
        "mcu": "nrf52840",
        "vendor": "ezurio",
        "external_flash": None,
        "bootloader": None,
    },
    "bl654_usb": {
        "name": "BL654 USB (451-00004)",
        "mcu": "nrf52840",
        "vendor": "ezurio",
        "external_flash": None,
        "bootloader": None,
    },
    "blueclover_plt_demo_v2": {
        "name": "Blue Clover PLT Demo V2 nRF52832",
        "mcu": "nrf52832",
        "vendor": "bcdevices",
        "external_flash": None,
        "bootloader": None,
    },
    "bt510": {
        "name": "Sentrius BT510 Sensor",
        "mcu": "nrf52840",
        "vendor": "ezurio",
        "external_flash": None,
        "bootloader": None,
    },
    "bt610": {
        "name": "Sentrius BT610 Sensor",
        "mcu": "nrf52840",
        "vendor": "ezurio",
        "external_flash": {
            "label": "mx25r64",
            "size": 0x4000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": None,
    },
    "bytesensi_l": {
        "name": "byteSENSI-L",
        "mcu": "nrf52832",
        "vendor": "bytesatwork",
        "external_flash": {
            "label": "nor_flash",
            "size": 0x4000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": None,
    },
    "contextualelectronics_abc": {
        "name": "Advanced BLE Cell",
        "mcu": "nrf52840",
        "vendor": "contextualelectronics",
        "external_flash": None,
        "bootloader": None,
    },
    "croxel_cx1825": {
        "name": "CX1825 nRF52840",
        "mcu": "nrf52840",
        "vendor": "croxel",
        "external_flash": None,
        "bootloader": None,
    },
    "ctcc": {
        "name": "Connectivity Card nRF52840",
        "mcu": "nrf52840",
        "vendor": "Unknown",
        "external_flash": None,
        "bootloader": None,
    },
    "decawave_dwm1001_dev": {
        "name": "Decawave DWM1001",
        "mcu": "nrf52832",
        "vendor": "qorvo",
        "external_flash": None,
        "bootloader": None,
    },
    "degu_evk": {
        "name": "Degu Evaluation Kit",
        "mcu": "nrf52840",
        "vendor": "atmarktechno",
        "external_flash": None,
        "bootloader": None,
    },
    "ebyte_e73_tbb": {
        "name": "E73-TBB",
        "mcu": "nrf52832",
        "vendor": "ebyte",
        "external_flash": None,
        "bootloader": None,
    },
    "holyiot_yj16019": {
        "name": "YJ-16019",
        "mcu": "nrf52832",
        "vendor": "holyiot",
        "external_flash": None,
        "bootloader": None,
    },
    "mg100": {
        "name": "Sentrius™ MG100 Gateway",
        "mcu": "nrf52840",
        "vendor": "ezurio",
        "external_flash": {
            "label": "mx25r64",
            "size": 0x4000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": None,
    },
    "micromod": {
        "name": "MicroMod board Processor",
        "mcu": "nrf52840",
        "vendor": "sparkfun",
        "external_flash": {
            "label": "w25q128jv",
            "size": 0x8000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": None,
    },
    "nrf21540dk": {
        "name": "nRF21540 DK",
        "mcu": "nrf52840",
        "vendor": "nordic",
        "external_flash": None,
        "bootloader": None,
    },
    "nrf52810dmouse": {
        "name": "nrf52810dmouse",
        "mcu": "nrf52810",
        "vendor": "nordic",
        "external_flash": None,
        "bootloader": None,
    },
    "nrf52820dongle": {
        "name": "nrf52820dongle",
        "mcu": "nrf52820",
        "vendor": "nordic",
        "external_flash": None,
        "bootloader": None,
    },
    "nrf52832_mdk": {
        "name": "nRF52832-mdk",
        "mcu": "nrf52832",
        "vendor": "makerdiary",
        "external_flash": None,
        "bootloader": None,
    },
    "nrf52833dk": {
        "name": "nRF52833 DK",
        "mcu": "nrf52820",
        "vendor": "nordic",
        "external_flash": None,
        "bootloader": None,
    },
    "nrf52833dongle": {
        "name": "nrf52833dongle",
        "mcu": "nrf52833",
        "vendor": "nordic",
        "external_flash": None,
        "bootloader": None,
    },
    "nrf52840_blip": {
        "name": "Labs Blip",
        "mcu": "nrf52840",
        "vendor": "electronut",
        "external_flash": None,
        "bootloader": None,
    },
    "nrf52840_mdk": {
        "name": "nRF52840-mdk",
        "mcu": "nrf52840",
        "vendor": "makerdiary",
        "external_flash": {
            "label": "mx25r64",
            "size": 0x4000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": None,
    },
    "nrf52840_mdk_usb_dongle": {
        "name": "nRF52840 MDK USB Dongle",
        "mcu": "nrf52840",
        "vendor": "makerdiary",
        "external_flash": None,
        "bootloader": None,
    },
    "nrf52840_papyr": {
        "name": "Labs Papyr",
        "mcu": "nrf52840",
        "vendor": "electronut",
        "external_flash": None,
        "bootloader": None,
    },
    "nrf52840dk": {
        "name": "nRF52840 DK",
        "mcu": "nrf52840",
        "vendor": "nordic",
        "external_flash": {
            "label": "mx25r64",
            "size": 0x4000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": None,
    },
    "nrf52840dongle": {
        "name": "nRF52840 Dongle",
        "mcu": "nrf52840",
        "vendor": "nordic",
        "external_flash": None,
        "bootloader": None,
    },
    "nrf52840gmouse": {
        "name": "nrf52840gmouse",
        "mcu": "nrf52840",
        "vendor": "nordic",
        "external_flash": None,
        "bootloader": None,
    },
    "nrf52_adafruit_feather": {
        "name": "nRF52 Adafruit Feather",
        "mcu": "nrf52832",
        "vendor": "adafruit",
        "external_flash": None,
        "bootloader": None,
    },
    "nrf52_blenano2": {
        "name": "Redbear Labs Nano v2",
        "mcu": "nrf52832",
        "vendor": "particle",
        "external_flash": None,
        "bootloader": None,
    },
    "nrf52_sparkfun": {
        "name": "nRF52832 breakout",
        "mcu": "nrf52832",
        "vendor": "sparkfun",
        "external_flash": None,
        "bootloader": None,
    },
    "nrf52_vbluno52": {
        "name": "nRF52-VBLUno52",
        "mcu": "nrf52832",
        "vendor": "vngiotlab",
        "external_flash": None,
        "bootloader": None,
    },
    "nrf52dk": {
        "name": "nRF52 DK",
        "mcu": "nrf52810",
        "vendor": "nordic",
        "external_flash": None,
        "bootloader": None,
    },
    "nrf52dmouse": {
        "name": "nrf52dmouse",
        "mcu": "nrf52832",
        "vendor": "nordic",
        "external_flash": None,
        "bootloader": None,
    },
    "nrf52kbd": {
        "name": "nrf52kbd",
        "mcu": "nrf52832",
        "vendor": "nordic",
        "external_flash": None,
        "bootloader": None,
    },
    "nrf5340_audio_dk": {
        "name": "nRF5340 Audio DK",
        "mcu": "nrf5340",
        "vendor": "nordic",
        "external_flash": None,
        "bootloader": None,
    },
    "nrf5340dk": {
        "name": "nRF5340 DK",
        "mcu": "nrf5340",
        "vendor": "nordic",
        "external_flash": {
            "label": "mx25r64",
            "size": 0x4000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": None,
    },
    "nrf54h20dk": {
        "name": "nRF54H20 DK",
        "mcu": "nrf54h20",
        "vendor": "nordic",
        "external_flash": {
            "label": "mx25uw63",
            "size": 0x4000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": None,
    },
    "nrf54l15dk": {
        "name": "nRF54L15 DK",
        "mcu": "nrf54l05",
        "vendor": "nordic",
        "external_flash": {
            "label": "mx25r64",
            "size": 0x4000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": None,
    },
    "nrf54l20pdk": {
        "name": "nRF54L20 PDK",
        "mcu": "nrf54l20",
        "vendor": "nordic",
        "external_flash": None,
        "bootloader": None,
    },
    "nrf7002dk": {
        "name": "nRF7002 DK",
        "mcu": "nrf5340",
        "vendor": "nordic",
        "external_flash": {
            "label": "mx25r64",
            "size": 0x4000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": None,
    },
    "nrf9160dk": {
        "name": "nRF9160 DK",
        "mcu": "nrf52840",
        "vendor": "nordic",
        "external_flash": None,
        "bootloader": None,
    },
    "pan1770_evb": {
        "name": "PAN1770 Evaluation Board",
        "mcu": "nrf52840",
        "vendor": "panasonic",
        "external_flash": None,
        "bootloader": None,
    },
    "pan1780_evb": {
        "name": "PAN1780 Evaluation Board",
        "mcu": "nrf52840",
        "vendor": "panasonic",
        "external_flash": None,
        "bootloader": None,
    },
    "pan1781_evb": {
        "name": "PAN1781 Evaluation Board",
        "mcu": "nrf52820",
        "vendor": "panasonic",
        "external_flash": None,
        "bootloader": None,
    },
    "pan1782_evb": {
        "name": "PAN1782 Evaluation Board",
        "mcu": "nrf52833",
        "vendor": "panasonic",
        "external_flash": None,
        "bootloader": None,
    },
    "pan1783_evb": {
        "name": "PAN1783 Evaluation Board",
        "mcu": "nrf5340",
        "vendor": "panasonic",
        "external_flash": {
            "label": "mx25r64",
            "size": 0x4000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": None,
    },
    "pan1783a_evb": {
        "name": "PAN1783A Evaluation Board",
        "mcu": "nrf5340",
        "vendor": "panasonic",
        "external_flash": {
            "label": "mx25r64",
            "size": 0x4000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": None,
    },
    "pan1783a_pa_evb": {
        "name": "PAN1783A-PA Evaluation Board",
        "mcu": "nrf5340",
        "vendor": "panasonic",
        "external_flash": {
            "label": "mx25r64",
            "size": 0x4000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": None,
    },
    "particle_argon": {
        "name": "Argon",
        "mcu": "nrf52840",
        "vendor": "particle",
        "external_flash": {
            "label": "mx25l32",
            "size": 0x2000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": None,
    },
    "particle_boron": {
        "name": "Boron",
        "mcu": "nrf52840",
        "vendor": "particle",
        "external_flash": {
            "label": "mx25l32",
            "size": 0x2000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": None,
    },
    "particle_xenon": {
        "name": "Xenon",
        "mcu": "nrf52840",
        "vendor": "particle",
        "external_flash": {
            "label": "mx25l32",
            "size": 0x2000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": None,
    },
    "pinetime_devkit0": {
        "name": "PineTime DevKit0",
        "mcu": "nrf52832",
        "vendor": "pine64",
        "external_flash": {
            "label": "xt25fb32",
            "size": 0x2000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": None,
    },
    "pinnacle_100_dvk": {
        "name": "Pinnacle 100 DVK",
        "mcu": "nrf52840",
        "vendor": "ezurio",
        "external_flash": {
            "label": "mx25r64",
            "size": 0x4000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": None,
    },
    "rak4631": {
        "name": "RAK4631",
        "mcu": "nrf52840",
        "vendor": "rakwireless",
        "external_flash": None,
        "bootloader": None,
    },
    "rak5010": {
        "name": "RAK5010",
        "mcu": "nrf52840",
        "vendor": "rakwireless",
        "external_flash": {
            "label": "is25wp064a",
            "size": 0x4000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": None,
    },
    "raytac_mdbt50q_db_33": {
        "name": "MDBT50Q-DB-33",
        "mcu": "nrf52833",
        "vendor": "raytac",
        "external_flash": None,
        "bootloader": None,
    },
    "raytac_mdbt50q_db_40": {
        "name": "MDBT50Q-DB-40",
        "mcu": "nrf52840",
        "vendor": "raytac",
        "external_flash": None,
        "bootloader": None,
    },
    "raytac_mdbt53_db_40": {
        "name": "MDBT53-DB-40",
        "mcu": "nrf5340",
        "vendor": "raytac",
        "external_flash": None,
        "bootloader": None,
    },
    "raytac_mdbt53v_db_40": {
        "name": "MDBT53V-DB-40",
        "mcu": "nrf5340",
        "vendor": "raytac",
        "external_flash": None,
        "bootloader": None,
    },
    "reel_board": {
        "name": "reel board",
        "mcu": "nrf52840",
        "vendor": "phytec",
        "external_flash": None,
        "bootloader": None,
    },
    "ruuvi_ruuvitag": {
        "name": "RuuviTag",
        "mcu": "nrf52832",
        "vendor": "ruuvi",
        "external_flash": None,
        "bootloader": None,
    },
    "thingy52": {
        "name": "Thingy:52",
        "mcu": "nrf52832",
        "vendor": "nordic",
        "external_flash": None,
        "bootloader": None,
    },
    "thingy53": {
        "name": "Thingy:53",
        "mcu": "nrf5340",
        "vendor": "nordic",
        "external_flash": {
            "label": "mx25r64",
            "size": 0x4000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": None,
    },
    "thingy91": {
        "name": "thingy91",
        "mcu": "nrf52840",
        "vendor": "nordic",
        "external_flash": None,
        "bootloader": None,
    },
    "thingy91x": {
        "name": "thingy91x",
        "mcu": "nrf5340",
        "vendor": "nordic",
        "external_flash": {
            "label": "flash_ext",
            "size": 0x10000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": None,
    },
    "ubx_bmd300eval": {
        "name": "EVK-BMD-30/35: BMD-300-EVAL, BMD-301-EVAL, and BMD-350-EVAL",
        "mcu": "nrf52832",
        "vendor": "u-blox",
        "external_flash": None,
        "bootloader": None,
    },
    "ubx_bmd330eval": {
        "name": "EVK-BMD-330: BMD-330-EVAL",
        "mcu": "nrf52810",
        "vendor": "u-blox",
        "external_flash": None,
        "bootloader": None,
    },
    "ubx_bmd340eval": {
        "name": "EVK-BMD-34/38: BMD-340-EVAL and BMD-341-EVAL",
        "mcu": "nrf52840",
        "vendor": "u-blox",
        "external_flash": {
            "label": "mx25r64",
            "size": 0x4000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": None,
    },
    "ubx_bmd345eval": {
        "name": "EVK-BMD-34/38: BMD-345-EVAL",
        "mcu": "nrf52840",
        "vendor": "u-blox",
        "external_flash": {
            "label": "mx25r64",
            "size": 0x4000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": None,
    },
    "ubx_bmd360eval": {
        "name": "EVK-BMD-360: BMD-360-EVAL",
        "mcu": "nrf52811",
        "vendor": "u-blox",
        "external_flash": None,
        "bootloader": None,
    },
    "ubx_bmd380eval": {
        "name": "EVK-BMD-34/48: BMD-380-EVAL",
        "mcu": "nrf52840",
        "vendor": "u-blox",
        "external_flash": {
            "label": "mx25r64",
            "size": 0x4000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": None,
    },
    "ubx_evkannab1": {
        "name": "EVK-ANNA-B11x",
        "mcu": "nrf52832",
        "vendor": "u-blox",
        "external_flash": None,
        "bootloader": None,
    },
    "ubx_evkninab1": {
        "name": "EVK NINA-B11x",
        "mcu": "nrf52832",
        "vendor": "u-blox",
        "external_flash": None,
        "bootloader": None,
    },
    "ubx_evkninab3": {
        "name": "EVK-NINA-B3",
        "mcu": "nrf52840",
        "vendor": "u-blox",
        "external_flash": None,
        "bootloader": None,
    },
    "ubx_evkninab4": {
        "name": "EVK NINA-B40x",
        "mcu": "nrf52833",
        "vendor": "u-blox",
        "external_flash": None,
        "bootloader": None,
    },
    "we_proteus2ev": {
        "name": "Proteus-II-EV",
        "mcu": "nrf52832",
        "vendor": "wurth",
        "external_flash": None,
        "bootloader": None,
    },
    "we_proteus3ev": {
        "name": "Proteus-III-EV",
        "mcu": "nrf52840",
        "vendor": "wurth",
        "external_flash": None,
        "bootloader": None,
    },
    "xiao_ble": {
        "name": "XIAO BLE (Sense)",
        "mcu": "nrf52840",
        "vendor": "seeed",
        "external_flash": {
            "label": "p25q16h",
            "size": 0x1000000,
            "erase_block_size": 0x1000,
        },
        "bootloader": {
            "type": "adafruit_nrf52_sd140_v7",
            "partitions": [
                {"name": "softdevice", "address": 0x0, "size": 0x27000},
                {"name": "adafruit_bootloader", "address": 0xF4000, "size": 0xC000},
            ],
        },
    },
}
