CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_LOG=n
CONFIG_PRINTK=n
CONFIG_HW_CC3XX=n
CONFIG_BOOT_BANNER=n
CONFIG_SINGLE_APPLICATION_SLOT=y
CONFIG_BOOT_VALIDATE_SLOT0=n
CONFIG_BOOT_UPGRADE_ONLY=y
CONFIG_MCUBOOT_SERIAL=y
CONFIG_BOOT_SERIAL_ENTRANCE_GPIO=n
CONFIG_BOOT_SERIAL_CDC_ACM=y
CONFIG_BOOT_ECDSA_TINYCRYPT=y
CONFIG_BOOT_SERIAL_IMG_GRP_HASH=n
CONFIG_BOOT_SERIAL_WAIT_FOR_DFU=y
CONFIG_BOOT_SERIAL_WAIT_FOR_DFU_TIMEOUT=30000
CONFIG_BOOT_ERASE_PROGRESSIVELY=y
CONFIG_BOOT_WATCHDOG_FEED=n
