FROM esphome/esphome-base-amd64:3.4.0


RUN export DEBIAN_FRONTEND=noninteractive \
 && apt-get update \
 && apt-get install -y --no-install-recommends \
     python3-wheel net-tools \
     clang-format-7 clang-tidy nano \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt requirements_test.txt docker/platformio_install_deps.py platformio.ini /
RUN pip3 install --disable-pip-version-check --no-cache-dir -r /requirements.txt -r /requirements_test.txt \
 && rm -rf /tmp/pip-tmp \
 && /platformio_install_deps.py /platformio.ini
