FROM ubuntu:bionic

RUN apt-get update && apt-get install -y --no-install-recommends \
        python \
        python-pip \
        python-setuptools \
        python-pil \
        git \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/*rm -rf /var/lib/apt/lists/* /tmp/* && \
    pip install --no-cache-dir platformio && \
    platformio settings set enable_telemetry No && \
    platformio settings set check_libraries_interval 1000000 && \
    platformio settings set check_platformio_interval 1000000 && \
    platformio settings set check_platforms_interval 1000000

COPY docker/platformio.ini /pio/platformio.ini
RUN platformio run -d /pio; rm -rf /pio

COPY requirements.txt /requirements.txt

RUN pip install --no-cache-dir -r /requirements.txt
