ARG BUILD_FROM=esphome/esphome-lint-base:latest
FROM ${BUILD_FROM}

COPY requirements.txt requirements_optional.txt requirements_test.txt docker/platformio_install_deps.py  platformio.ini /
RUN \
    pip3 install --no-cache-dir -r /requirements.txt -r /requirements_optional.txt -r /requirements_test.txt \
    && /platformio_install_deps.py /platformio.ini

VOLUME ["/esphome"]
WORKDIR /esphome
