FROM esphome/esphome-base-amd64:2.6.0

COPY . .

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        python3-wheel \
        net-tools \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspaces
ENV SHELL /bin/bash
