#!/usr/bin/env bash

# the Docker repository tag being built.
declare CACHE_TAG
echo "CACHE_TAG: ${CACHE_TAG}"
# the name and tag of the Docker repository being built. (This variable is a combination of DOCKER_REPO:CACHE_TAG.)
declare IMAGE_NAME
echo "IMAGE_NAME: ${IMAGE_NAME}"
# the architecture to build
declare BUILD_ARCH
echo "BUILD_ARCH: ${BUILD_ARCH}"
# whether this is a hassio build
declare IS_HASSIO
echo "IS_HASSIO: ${IS_HASSIO}"
echo "PWD: $PWD"

if [[ ${IS_HASSIO} = "YES" ]]; then
    docker build \
      --build-arg "BUILD_FROM=esphome/esphome-hassio-base-${BUILD_ARCH}:1.4.3" \
      --build-arg "BUILD_VERSION=${CACHE_TAG}" \
      -t "${IMAGE_NAME}" -f ../docker/Dockerfile.hassio ..
else
    docker build \
      --build-arg "BUILD_FROM=esphome/esphome-base-${BUILD_ARCH}:1.4.3" \
      -t "${IMAGE_NAME}" -f ../docker/Dockerfile ..
fi
