#!/usr/bin/env bash

# the architecture to build
declare BUILD_ARCH

echo "BUILD_ARCH: ${BUILD_ARCH}"

if [[ ${BUILD_ARCH} = "amd64" ]]; then
    echo "No qemu required..."
    exit 0
fi
if [[ ${BUILD_ARCH} = "i386" ]]; then
    echo "No qemu required..."
    exit 0
fi

echo "Installing qemu..."
docker run --rm --privileged multiarch/qemu-user-static:register --reset
