import esphome.codegen as cg
from esphome.components import binary_sensor
import esphome.config_validation as cv

from .. import OpenTherm42Hub
from ..const import (
    CONF_CONTROL_AND_STATUS_INFORMATION_APPLICATION_SPECIFIC_FAULT_FLAGS_AIR_PRESS_FAULT,
    CONF_CONTROL_AND_STATUS_INFORMATION_APPLICATION_SPECIFIC_FAULT_FLAGS_GAS_FLAME_FAULT,
    CONF_CONTROL_AND_STATUS_INFORMATION_APPLICATION_SPECIFIC_FAULT_FLAGS_LOCKOUT_RESET,
    CONF_CONTROL_AND_STATUS_INFORMATION_APPLICATION_SPECIFIC_FAULT_FLAGS_LOW_WATER_PRESS,
    CONF_CONTROL_AND_STATUS_INFORMATION_APPLICATION_SPECIFIC_FAULT_FLAGS_SERVICE_REQUEST,
    CONF_CONTROL_AND_STATUS_INFORMATION_APPLICATION_SPECIFIC_FAULT_FLAGS_VENTILATION_HEAT_RECOVERY_EXHAUST_FAN_FAULT,
    CONF_CONTROL_AND_STATUS_INFORMATION_APPLICATION_SPECIFIC_FAULT_FLAGS_VENTILATION_HEAT_RECOVERY_FROST_PROTECTION,
    CONF_CONTROL_AND_STATUS_INFORMATION_APPLICATION_SPECIFIC_FAULT_FLAGS_VENTILATION_HEAT_RECOVERY_INLET_FAN_FAULT,
    CONF_CONTROL_AND_STATUS_INFORMATION_APPLICATION_SPECIFIC_FAULT_FLAGS_VENTILATION_HEAT_RECOVERY_SERVICE_REQUEST,
    CONF_CONTROL_AND_STATUS_INFORMATION_APPLICATION_SPECIFIC_FAULT_FLAGS_WATER_OVER_TEMP,
    CONF_CONTROL_AND_STATUS_INFORMATION_BOILER_STATUS_CH2_MODE,
    CONF_CONTROL_AND_STATUS_INFORMATION_BOILER_STATUS_CH_MODE,
    CONF_CONTROL_AND_STATUS_INFORMATION_BOILER_STATUS_COOLING_STATUS,
    CONF_CONTROL_AND_STATUS_INFORMATION_BOILER_STATUS_DHW_MODE,
    CONF_CONTROL_AND_STATUS_INFORMATION_BOILER_STATUS_DIAGNOSTIC_SERVICE_INDICATION,
    CONF_CONTROL_AND_STATUS_INFORMATION_BOILER_STATUS_ELECTRICITY_PRODUCTION,
    CONF_CONTROL_AND_STATUS_INFORMATION_BOILER_STATUS_FAULT_INDICATION,
    CONF_CONTROL_AND_STATUS_INFORMATION_BOILER_STATUS_FLAME_STATUS,
    CONF_CONTROL_AND_STATUS_INFORMATION_SOLAR_STORAGE_MODE_AND_STATUS_FAULT_INDICATION,
    CONF_CONTROL_AND_STATUS_INFORMATION_STATUS_VENTILATION_HEAT_RECOVERY_BYPASS_AUTOMATIC_STATUS,
    CONF_CONTROL_AND_STATUS_INFORMATION_STATUS_VENTILATION_HEAT_RECOVERY_BYPASS_STATUS,
    CONF_CONTROL_AND_STATUS_INFORMATION_STATUS_VENTILATION_HEAT_RECOVERY_DIAGNOSTIC_INDICATION,
    CONF_CONTROL_AND_STATUS_INFORMATION_STATUS_VENTILATION_HEAT_RECOVERY_FAULT_INDICATION,
    CONF_CONTROL_AND_STATUS_INFORMATION_STATUS_VENTILATION_HEAT_RECOVERY_FREE_VENTILATION_STATUS,
    CONF_CONTROL_AND_STATUS_INFORMATION_STATUS_VENTILATION_HEAT_RECOVERY_VENTILATION_MODE,
)

CONF_OPENTHERM42_ID = "opentherm42_id"

# All of Class 1's binary_sensors are boiler-reported status bits: on a failed conversation, every
# configured bit here must show unknown rather than keep a stale reading -- see the hub's
# FlagReadBits::invalidate().
DESCRIPTIONS: dict[str, str] = {
    # §5.3.1 Class 1, ID 0 LB bit 0: fault indication [ no fault, fault ]
    CONF_CONTROL_AND_STATUS_INFORMATION_BOILER_STATUS_FAULT_INDICATION: "problem",
    # §5.3.1 Class 1, ID 0 LB bit 1: CH mode [ CH not active, CH active ]
    CONF_CONTROL_AND_STATUS_INFORMATION_BOILER_STATUS_CH_MODE: "running",
    # §5.3.1 Class 1, ID 0 LB bit 2: DHW mode [ DHW not active, DHW active ]
    CONF_CONTROL_AND_STATUS_INFORMATION_BOILER_STATUS_DHW_MODE: "running",
    # §5.3.1 Class 1, ID 0 LB bit 3: Flame status [ flame off, flame on ]
    CONF_CONTROL_AND_STATUS_INFORMATION_BOILER_STATUS_FLAME_STATUS: "heat",
    # §5.3.1 Class 1, ID 0 LB bit 4: Cooling status [ cooling mode not active, cooling mode active ]
    CONF_CONTROL_AND_STATUS_INFORMATION_BOILER_STATUS_COOLING_STATUS: "running",
    # §5.3.1 Class 1, ID 0 LB bit 5: CH2 mode [ CH2 not active, CH2 active ]
    CONF_CONTROL_AND_STATUS_INFORMATION_BOILER_STATUS_CH2_MODE: "running",
    # §5.3.1 Class 1, ID 0 LB bit 6: diagnostic/service indication [no diagnostic/service, diagnostic/service event]
    CONF_CONTROL_AND_STATUS_INFORMATION_BOILER_STATUS_DIAGNOSTIC_SERVICE_INDICATION: "problem",
    # §5.3.1 Class 1, ID 0 LB bit 7: Electricity production [off, on]
    CONF_CONTROL_AND_STATUS_INFORMATION_BOILER_STATUS_ELECTRICITY_PRODUCTION: "running",
    # §5.3.1 Class 1, ID 70 LB bit 0: Fault indication [ no fault, fault ]
    CONF_CONTROL_AND_STATUS_INFORMATION_STATUS_VENTILATION_HEAT_RECOVERY_FAULT_INDICATION: "problem",
    # §5.3.1 Class 1, ID 70 LB bit 1: Ventilation mode [ not active, active ]
    CONF_CONTROL_AND_STATUS_INFORMATION_STATUS_VENTILATION_HEAT_RECOVERY_VENTILATION_MODE: "running",
    # §5.3.1 Class 1, ID 70 LB bit 2: Bypass status [ closed, open ]
    CONF_CONTROL_AND_STATUS_INFORMATION_STATUS_VENTILATION_HEAT_RECOVERY_BYPASS_STATUS: "opening",
    # §5.3.1 Class 1, ID 70 LB bit 3: Bypass automatic status [ manual, automatic ]
    CONF_CONTROL_AND_STATUS_INFORMATION_STATUS_VENTILATION_HEAT_RECOVERY_BYPASS_AUTOMATIC_STATUS: None,
    # §5.3.1 Class 1, ID 70 LB bit 4: Free ventilation status [ not active, active ]
    CONF_CONTROL_AND_STATUS_INFORMATION_STATUS_VENTILATION_HEAT_RECOVERY_FREE_VENTILATION_STATUS: "running",
    # §5.3.1 Class 1, ID 70 LB bit 6: Diagnostic indication [ no diagnostics, diagnostic event ]
    CONF_CONTROL_AND_STATUS_INFORMATION_STATUS_VENTILATION_HEAT_RECOVERY_DIAGNOSTIC_INDICATION: "problem",
    # §5.3.1 Class 1, ID 5 HB bit 0: Service request [ service not req'd, service required ]
    CONF_CONTROL_AND_STATUS_INFORMATION_APPLICATION_SPECIFIC_FAULT_FLAGS_SERVICE_REQUEST: "problem",
    # §5.3.1 Class 1, ID 5 HB bit 1: Lockout-reset [ remote reset disabled, remote reset enabled ]
    CONF_CONTROL_AND_STATUS_INFORMATION_APPLICATION_SPECIFIC_FAULT_FLAGS_LOCKOUT_RESET: None,
    # §5.3.1 Class 1, ID 5 HB bit 2: Low water press [ no WP fault, water pressure fault ]
    CONF_CONTROL_AND_STATUS_INFORMATION_APPLICATION_SPECIFIC_FAULT_FLAGS_LOW_WATER_PRESS: "problem",
    # §5.3.1 Class 1, ID 5 HB bit 3: Gas/flame fault [ no G/F fault, gas/flame fault ]
    CONF_CONTROL_AND_STATUS_INFORMATION_APPLICATION_SPECIFIC_FAULT_FLAGS_GAS_FLAME_FAULT: "problem",
    # §5.3.1 Class 1, ID 5 HB bit 4: Air press fault [ no AP fault, air pressure fault ]
    CONF_CONTROL_AND_STATUS_INFORMATION_APPLICATION_SPECIFIC_FAULT_FLAGS_AIR_PRESS_FAULT: "problem",
    # §5.3.1 Class 1, ID 5 HB bit 5: Water over-temp [ no OvT fault, over-temperature fault ]
    CONF_CONTROL_AND_STATUS_INFORMATION_APPLICATION_SPECIFIC_FAULT_FLAGS_WATER_OVER_TEMP: "problem",
    # §5.3.1 Class 1, ID 72 HB bit 0: Service request, ventilation/heat-recovery
    CONF_CONTROL_AND_STATUS_INFORMATION_APPLICATION_SPECIFIC_FAULT_FLAGS_VENTILATION_HEAT_RECOVERY_SERVICE_REQUEST: "problem",
    # §5.3.1 Class 1, ID 72 HB bit 1: Exhaust fan fault [ no fault, fault ]
    CONF_CONTROL_AND_STATUS_INFORMATION_APPLICATION_SPECIFIC_FAULT_FLAGS_VENTILATION_HEAT_RECOVERY_EXHAUST_FAN_FAULT: "problem",
    # §5.3.1 Class 1, ID 72 HB bit 2: Inlet fan fault [ no fault, fault ]
    CONF_CONTROL_AND_STATUS_INFORMATION_APPLICATION_SPECIFIC_FAULT_FLAGS_VENTILATION_HEAT_RECOVERY_INLET_FAN_FAULT: "problem",
    # §5.3.1 Class 1, ID 72 HB bit 3: Frost protection [ not active, active ]
    CONF_CONTROL_AND_STATUS_INFORMATION_APPLICATION_SPECIFIC_FAULT_FLAGS_VENTILATION_HEAT_RECOVERY_FROST_PROTECTION: "cold",
    # §5.3.1 Class 1, ID 101 LB bit 0: fault indication
    CONF_CONTROL_AND_STATUS_INFORMATION_SOLAR_STORAGE_MODE_AND_STATUS_FAULT_INDICATION: "problem",
}

TYPES: dict[str, cv.Schema] = {
    marker: binary_sensor.binary_sensor_schema(device_class=device_class)
    if device_class
    else binary_sensor.binary_sensor_schema()
    for marker, device_class in DESCRIPTIONS.items()
}

CONFIG_SCHEMA = cv.Schema(
    {
        cv.GenerateID(CONF_OPENTHERM42_ID): cv.use_id(OpenTherm42Hub),
        **{cv.Optional(marker): schema for marker, schema in TYPES.items()},
    }
)


async def to_code(config: dict) -> None:
    hub = await cg.get_variable(config[CONF_OPENTHERM42_ID])
    for marker in TYPES:
        if (marker_config := config.get(marker)) is not None:
            var = await binary_sensor.new_binary_sensor(marker_config)
            cg.add(getattr(hub, f"set_{marker}_binary_sensor")(var))
