apiVersion: v1
kind: Secret
metadata:
  name: {{ include "esphome.fullname" . }}
  labels:
    {{- include "esphome.labels" . | nindent 4 }}
data:
  USERNAME: "{{ .Values.esphome.settings.username | b64enc }}"
  PASSWORD: "{{ .Values.esphome.settings.password | b64enc }}"
  ESPHOME_DASHBOARD_RELATIVE_URL: "{{ .Values.esphome.settings.relative_url | b64enc }}"
  ESPHOME_DASHBOARD_USE_PING: "{{ .Values.esphome.settings.use_ping | b64enc }}"
  ESPHOME_DASHBOARD_USE_MQTT: "{{ .Values.esphome.settings.use_mqtt | b64enc }}"
  DISABLE_HA_AUTHENTICATION: "{{ .Values.esphome.settings.disable_ha_auth | b64enc }}"
  ESPHOME_STREAMER_MODE: "{{ .Values.esphome.settings.streamer_mode | b64enc }}"









