apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "esphome.fullname" . }}
  labels:
    {{- include "esphome.labels" . | nindent 4 }}
spec:
  serviceName: {{include "esphome.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "esphome.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "esphome.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "esphome.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - secretRef:
             name: {{ include "esphome.fullname" . }}
          ports:
            - name: http
              containerPort: 6052
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- with .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end}}
          {{- with .Values.volumeMounts }}
          volumeMounts:
          - name: {{include "esphome.fullname" . }}
            mountPath: /config
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- if  .Values.persistence.enabled }}
      volumes:
        - name: {{ include "esphome.fullname" . }}
          emptyDir: {}
    {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "esphome.fullname" . }}
      spec:
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        accessModes:
          - {{ .Values.persistence.accessMode }}
        {{- if .Values.persistence.existingVolume }}
        volumeName: {{ .Values.persistence.existingVolume }}
        {{- end }}
        {{- if or .Values.persistence.matchLabels (.Values.persistence.matchExpressions) }}
        selector:
          {{- if .Values.persistence.matchLabels }}
          matchLabels:
          {{ toYaml .Values.persistence.matchLabels | indent 8 }}
          {{- end -}}
          {{- if .Values.persistence.matchExpressions }}
          matchExpressions:
            {{ toYaml .Values.persistence.matchExpressions | indent 8 }}
          {{- end -}}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
  {{- end }}
