#!/usr/bin/env python3
"""Generate updated requirements file."""

from __future__ import annotations

import os
from pathlib import Path
import sys
import tomllib


def main() -> int:
    """Run the script."""
    if not os.path.isfile("requirements.txt"):
        print("Run this from ESPHome root dir")
        return 1

    with open("pyproject.toml", "rb") as fp:
        data = tomllib.load(fp)
    dependencies: list[str] = sorted(data["project"]["dependencies"])

    output = [f"# Automatically generated by {Path(__file__).name}, do not edit\n\n"]
    output.append("\n".join(dependencies))
    output.append("\n")

    reqs = "".join(output)

    with open("requirements.txt", "w", encoding="utf-8") as fp:
        fp.write(reqs)
    return 0


if __name__ == "__main__":
    sys.exit(main())
