#!/bin/bash

components=()
platforms=()
count=0
for c_diff in $(git diff ${1}..${2} --name-only esphome/components); do
  ((count=count+1))
  base=`dirname $c_diff`
  base=${base#esphome/components/}
  component=`dirname ${base}`
  platform=`basename ${base}`

  if [[ "${component}" == "." ]]; then
    component=${platform}
  fi

  if [[ ! "${components[@]}" =~ "${component}" ]]; then
    components+=($component)
  fi
  if [[ "${platform}" != "${component}" ]] && [[ ! "${platforms[@]}" =~ "${platform}" ]]; then
    platforms+=($platform)
  fi
done

labels=()

echo "Components:"
for component in ${components[@]}; do
  echo "  ${component}"
  labels+=("component: $component")
done

echo ""
echo "Platforms:"
for platform in ${platforms[@]}; do
  echo "  ${platform}"
  labels+=($platform)
done

echo "Labels: ${labels[@]}"

output=$(printf '%s\n' "${labels[@]}" | jq -R . | jq -c -s .)

echo "::set-output name=labels::${output}"
