#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

set -x

esphome compile tests/test1.yaml
esphome compile tests/test2.yaml
esphome compile tests/test3.yaml
esphome compile tests/test4.yaml
esphome compile tests/test5.yaml
esphome compile tests/esp_now_device1.yaml compile
esphome compile tests/esp_now_device2.yaml compile
