#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/../tests/unit_tests_native/"

set -x

BUILD_DIR="build_unit_tests_native/"

[ -d $BUILD_DIR ] || {
	meson wrap update-db
	meson setup $BUILD_DIR
}
meson test -C $BUILD_DIR
