#include "remote_transmitter.h"
#include "esphome/core/application.h"
#include "esphome/core/log.h"

// clang-tidy cannot parse the Realtek SDK headers pulled in via ArduinoPrivate.h
#if defined(USE_RTL87XX) && !defined(CLANG_TIDY)

// ArduinoPrivate.h = Arduino.h + the SDK's mbed HAL (pwmout, gtimer) with the core's fixes for
// type-name collisions between the two (e.g. PinMode)
#include <ArduinoPrivate.h>
#ifndef USE_LIBRETINY_VARIANT_RTL8720C
#include <FreeRTOS.h>
#include <task.h>
#endif

namespace esphome::remote_transmitter {

static const char *const TAG = "remote_transmitter";

// The carrier is generated by the PWM peripheral instead of bit-banging the pin: software carrier
// generation requires disabling interrupts for the whole frame, but this core's micros() is derived
// from the FreeRTOS tick and freezes while interrupts are off, so the timing loop never advances and
// the watchdog resets the chip.
//
// The mark/space envelope is paced by a hardware gtimer interrupt chain rather than a busy-wait:
// each interrupt sets the next PWM duty and re-arms the timer for that item's duration, so the main
// task never blocks on timing and needs no priority boost. With non_blocking enabled, send_internal
// returns immediately and on_complete fires from loop().
//
// The PWM is driven through the SDK's pwmout HAL directly rather than the Arduino wiring layer:
// changing the carrier frequency via the wiring requires a GPIO/PWM pin mode round-trip, which
// use-after-frees the core's per-pin state (pinRemoveMode() frees without nulling) and corrupts the
// heap. pwmout_period_us() changes the frequency with no mode transitions.
//
// The AmebaZ2 PWM peripheral allocates its tick sources from the same gtimer pool that timer_api
// exposes (GTimer1..GTimer7). The pool is shrunk to exclude GTimer7 before the PWM claims its tick
// source, and GTimer7 paces the envelope -- so the two cannot collide.

#ifdef USE_LIBRETINY_VARIANT_RTL8720C
static constexpr uint32_t ENVELOPE_TIMER_ID = TIMER6;  // GTimer7
// Margin added to a transmission's expected duration before the waits in send_internal
// declare the timer chain stalled; generous so it only trips on a genuinely dead chain
static constexpr uint32_t STALL_MARGIN_MS = 1000;
// Longest single hardware one-shot armed; longer durations are chained in chunks. Well
// inside the hardware-validated range, and costs one ~microsecond ISR per 50ms of gap.
static constexpr uint32_t MAX_ONE_SHOT_US = 50000;
static uint8_t pwm_tick_sources[] = {GTimer1, GTimer2, GTimer3, GTimer4, GTimer5, GTimer6, 0xff};

// One envelope timer shared by all instances (MULTI_CONF): a second gtimer_init on the
// same timer id fails silently, so instances serialize on s_active_transmitter instead.
// NOLINTBEGIN(cppcoreguidelines-avoid-non-const-global-variables)
static gtimer_t s_envelope_timer;
static bool s_envelope_timer_ready = false;
static RemoteTransmitterComponent *volatile s_active_transmitter = nullptr;
// Deadline for the in-flight transmission (millis-based); only touched from the main task
static uint32_t s_expected_end_ms = 0;
// NOLINTEND(cppcoreguidelines-avoid-non-const-global-variables)

static void envelope_timer_isr(uint32_t arg) {
  reinterpret_cast<RemoteTransmitterComponent *>(arg)->advance_envelope_isr();
}
#endif  // USE_LIBRETINY_VARIANT_RTL8720C

void RemoteTransmitterComponent::setup() {
  // Deliberately no pin_->setup(): registering the pin as GPIO claims it in the SDK's pin
  // management, and the pad is then never handed over to the PWM peripheral -- pwmout_init()
  // must own the pin from the start.
  PinInfo *info = pinInfo(this->pin_->get_pin());
  if (info == nullptr || !pinSupported(info, PIN_PWM)) {
    // checked here because the AmebaZ (RTL8710B) SDK does not report PWM init failure
    ESP_LOGE(TAG, "Pin %u is not PWM-capable", this->pin_->get_pin());
    this->mark_failed();
    return;
  }
  auto *pwm = new pwmout_t();
  this->pwm_ = pwm;
  pwmout_init(pwm, static_cast<PinName>(info->gpio));
#ifdef USE_LIBRETINY_VARIANT_RTL8720C
  // only the AmebaZ2 SDK's pwmout_s reports init success
  if (!pwm->is_init) {
    ESP_LOGE(TAG, "PWM init failed on pin %u", this->pin_->get_pin());
    delete pwm;
    this->pwm_ = nullptr;
    this->mark_failed();
    return;
  }
#endif
#ifdef USE_LIBRETINY_VARIANT_RTL8720C
  // Shrink the PWM tick-source pool before the period claim below so GTimer7 stays free.
  // pwmout_init just registered the full pool (a static latch inside pwmout_api).
  hal_pwm_comm_tick_source_list(pwm_tick_sources);
#endif
  pwmout_period_us(pwm, 26);  // placeholder; the real carrier period is set per transmission
  pwmout_write(pwm, this->pin_->is_inverted() ? 1.0f : 0.0f);
#ifdef USE_LIBRETINY_VARIANT_RTL8720C
  if (!s_envelope_timer_ready) {
    gtimer_init(&s_envelope_timer, ENVELOPE_TIMER_ID);
    s_envelope_timer_ready = true;
  }
#endif
  this->disable_loop();  // loop() is only needed while a non-blocking completion is pending
}

void RemoteTransmitterComponent::dump_config() {
  ESP_LOGCONFIG(TAG,
                "Remote Transmitter:\n"
                "  Carrier Duty: %u%%",
                this->carrier_duty_percent_);
#ifdef USE_LIBRETINY_VARIANT_RTL8720C
  ESP_LOGCONFIG(TAG, "  Non-blocking: %s", YESNO(this->non_blocking_));
#endif
  LOG_PIN("  Pin: ", this->pin_);
}

void RemoteTransmitterComponent::digital_write(bool value) {
  if (this->pwm_ == nullptr)
    return;
#ifdef USE_LIBRETINY_VARIANT_RTL8720C
  if (this->transmitting_)
    return;
#endif
  pwmout_write(static_cast<pwmout_t *>(this->pwm_), (value != this->pin_->is_inverted()) ? 1.0f : 0.0f);
}

#ifdef USE_LIBRETINY_VARIANT_RTL8720C
// Arms the shared envelope timer for one duration, chaining anything longer than
// MAX_ONE_SHOT_US as consecutive one-shots: repeat gaps are unbounded user config and the
// SDK's us->tick conversion lives in ROM with unverified headroom. ISR-safe.
void RemoteTransmitterComponent::arm_envelope_timer_(uint32_t duration_us) {
  // clamp to 1us: a zero-length one-shot never fires and would stall the chain
  const uint32_t chunk = std::max(uint32_t(1), std::min(duration_us, MAX_ONE_SHOT_US));
  this->isr_wait_remaining_ = duration_us - chunk;
  gtimer_start_one_shout(&s_envelope_timer, chunk, (void *) envelope_timer_isr, (uint32_t) this);
}

// Recovery when the timer chain stops advancing (e.g. gtimer_init failed silently -- it
// returns void): stop the timer, idle the pin, release the serialization token. Harmless if
// the chain completed between the deadline check and this call -- every step is then a no-op.
void RemoteTransmitterComponent::abort_stalled_chain_() {
  gtimer_stop(&s_envelope_timer);
  pwmout_write(static_cast<pwmout_t *>(this->pwm_), this->isr_space_duty_);
  this->transmitting_ = false;
  s_active_transmitter = nullptr;
  this->status_set_warning("envelope timer stalled");
  ESP_LOGE(TAG, "Envelope timer stalled; transmission aborted");
}

// Writes the duty for one envelope item and arms the timer for its duration.
// Runs in ISR context (and once from send_internal to kick the chain): no logging, no allocation.
void RemoteTransmitterComponent::start_isr_item_(size_t index) {
  const int32_t item = this->isr_data_[index];
  pwmout_write(static_cast<pwmout_t *>(this->pwm_), item > 0 ? this->isr_mark_duty_ : this->isr_space_duty_);
  this->arm_envelope_timer_(uint32_t(item > 0 ? item : -item));
}

void RemoteTransmitterComponent::advance_envelope_isr() {
  if (this->isr_wait_remaining_ > 0) {
    // continue a duration longer than one hardware one-shot
    this->arm_envelope_timer_(this->isr_wait_remaining_);
    return;
  }
  if (this->isr_in_gap_) {
    // inter-repeat gap elapsed; restart the item chain
    this->isr_in_gap_ = false;
    this->isr_index_ = 0;
    this->start_isr_item_(0);
    return;
  }
  this->isr_index_++;
  if (this->isr_index_ < this->isr_data_.size()) {
    this->start_isr_item_(this->isr_index_);
    return;
  }
  // end of one repetition
  pwmout_write(static_cast<pwmout_t *>(this->pwm_), this->isr_space_duty_);
  if (this->isr_repeats_left_ > 1) {
    this->isr_repeats_left_--;
    this->isr_index_ = 0;
    if (this->isr_send_wait_ > 0) {
      this->isr_in_gap_ = true;
      this->arm_envelope_timer_(this->isr_send_wait_);
    } else {
      this->start_isr_item_(0);
    }
    return;
  }
  this->transmitting_ = false;
  s_active_transmitter = nullptr;
}

void RemoteTransmitterComponent::send_internal(uint32_t send_times, uint32_t send_wait) {
  if (this->pwm_ == nullptr) {
    ESP_LOGW(TAG, "Cannot send: PWM not initialized");
    return;
  }
  // A transmission may still be in flight (this instance or another sharing the timer);
  // wait it out. Its frame stays intact: each ISR reads that instance's isr_data_ copy.
  // Bounded so a dead chain degrades to an aborted send instead of wedging the device,
  // and yielding -- the hardware timer owns the timing, polling granularity is irrelevant.
  // Deferred completions are reported here so they are never coalesced; a completion
  // automation may itself start a new send on this instance, so wait and flush until the
  // transmitter is truly idle.
  while (true) {
    while (s_active_transmitter != nullptr) {
      if ((int32_t) (millis() - s_expected_end_ms) > 0) {
        s_active_transmitter->abort_stalled_chain_();
        break;
      }
      App.feed_wdt();
      delay(1);
    }
    if (!this->complete_pending_)
      break;
    this->complete_pending_ = false;
    this->complete_trigger_.trigger();
  }
  if (send_times == 0) {
    // parity with the loop-based implementations: transmit nothing, but both triggers
    // still fire so an on_complete-sequenced automation does not stall
    this->transmit_trigger_.trigger();
    this->complete_trigger_.trigger();
    return;
  }
  ESP_LOGD(TAG, "Sending remote code");
  const uint32_t carrier_frequency = this->temp_.get_carrier_frequency();
  // unmodulated protocols (no carrier or 100% duty) drive the pin constantly during marks
  float mark_duty =
      (carrier_frequency > 0 && this->carrier_duty_percent_ < 100) ? this->carrier_duty_percent_ / 100.0f : 1.0f;
  float space_duty = 0.0f;
  if (this->pin_->is_inverted()) {
    mark_duty = 1.0f - mark_duty;
    space_duty = 1.0f;
  }
  auto *pwm = static_cast<pwmout_t *>(this->pwm_);
  if (carrier_frequency > 0 && carrier_frequency != this->current_carrier_frequency_) {
    // round(1000000/freq), clamped like the bit-bang path so a bad lambda can't hand the SDK a zero period
    const uint32_t period = std::max(uint32_t(1), (1000000UL + carrier_frequency / 2) / carrier_frequency);
    pwmout_period_us(pwm, period);
    this->current_carrier_frequency_ = carrier_frequency;
  }
  // own copy: with non_blocking the caller may re-encode temp_ while this frame is in flight
  this->isr_data_.assign(this->temp_.get_data().begin(), this->temp_.get_data().end());
  if (this->isr_data_.empty()) {
    ESP_LOGW(TAG, "Empty data");
    this->transmit_trigger_.trigger();
    this->complete_trigger_.trigger();
    return;
  }
  this->isr_mark_duty_ = mark_duty;
  this->isr_space_duty_ = space_duty;
  this->isr_repeats_left_ = send_times;
  this->isr_send_wait_ = send_wait;
  this->isr_index_ = 0;
  this->isr_in_gap_ = false;
  uint64_t frame_us = 0;
  for (int32_t item : this->isr_data_)
    frame_us += uint32_t(item > 0 ? item : -item);
  const uint64_t total_us = frame_us * send_times + uint64_t(send_wait) * (send_times - 1);
  s_expected_end_ms = millis() + uint32_t(total_us / 1000) + STALL_MARGIN_MS;
  this->transmit_trigger_.trigger();
  this->transmitting_ = true;
  s_active_transmitter = this;
  this->start_isr_item_(0);
  if (this->non_blocking_) {
    this->complete_pending_ = true;
    this->enable_loop();
    return;
  }
  bool stalled = false;
  while (this->transmitting_) {
    if ((int32_t) (millis() - s_expected_end_ms) > 0) {
      this->abort_stalled_chain_();
      stalled = true;
      break;
    }
    App.feed_wdt();
    delay(1);
  }
  if (!stalled)
    this->status_clear_warning();
  this->complete_pending_ = false;
  this->complete_trigger_.trigger();
}

void RemoteTransmitterComponent::loop() {
  if (!this->complete_pending_) {
    this->disable_loop();
    return;
  }
  if (this->transmitting_) {
    // non-blocking stall recovery: without this, a dead chain would leave the carrier
    // driven and on_complete unfired until the next send happened to abort it
    if ((int32_t) (millis() - s_expected_end_ms) <= 0)
      return;
    this->abort_stalled_chain_();
  } else {
    this->status_clear_warning();
  }
  this->complete_pending_ = false;
  this->complete_trigger_.trigger();
  this->disable_loop();
}

#else  // !USE_LIBRETINY_VARIANT_RTL8720C -- AmebaZ (RTL8710B): spin-based envelope, per-frame priority boost

void RemoteTransmitterComponent::await_target_time_() {
  const uint32_t current_time = micros();
  if (this->target_time_ == 0) {
    this->target_time_ = current_time;
  } else {
    while ((int32_t) (this->target_time_ - micros()) > 0) {
    }
  }
}

void RemoteTransmitterComponent::send_internal(uint32_t send_times, uint32_t send_wait) {
  if (this->pwm_ == nullptr) {
    ESP_LOGW(TAG, "Cannot send: PWM not initialized");
    return;
  }
  ESP_LOGD(TAG, "Sending remote code");
  const uint32_t carrier_frequency = this->temp_.get_carrier_frequency();
  // unmodulated protocols (no carrier or 100% duty) drive the pin constantly during marks
  float mark_duty =
      (carrier_frequency > 0 && this->carrier_duty_percent_ < 100) ? this->carrier_duty_percent_ / 100.0f : 1.0f;
  float space_duty = 0.0f;
  if (this->pin_->is_inverted()) {
    mark_duty = 1.0f - mark_duty;
    space_duty = 1.0f;
  }
  auto *pwm = static_cast<pwmout_t *>(this->pwm_);
  if (carrier_frequency > 0 && carrier_frequency != this->current_carrier_frequency_) {
    // round(1000000/freq), clamped like the bit-bang path so a bad lambda can't hand the SDK a zero period
    const uint32_t period = std::max(uint32_t(1), (1000000UL + carrier_frequency / 2) / carrier_frequency);
    pwmout_period_us(pwm, period);
    this->current_carrier_frequency_ = carrier_frequency;
  }
  this->transmit_trigger_.trigger();
  const UBaseType_t saved_priority = uxTaskPriorityGet(nullptr);
  for (uint32_t i = 0; i < send_times; i++) {
    // Boost task priority for the frame only, so WiFi/lwIP tasks can't preempt mid-frame and
    // merge adjacent marks. Interrupts stay enabled: micros() needs the FreeRTOS tick, and
    // ISR latency is within receiver tolerance.
    vTaskPrioritySet(nullptr, configMAX_PRIORITIES - 1);
    // Re-anchor every iteration: a late exit from the normal-priority gap wait must not
    // leave the schedule behind micros(), which would compress the next frame's leading items
    this->target_time_ = 0;
    for (int32_t item : this->temp_.get_data()) {
      const bool is_mark = item > 0;
      this->await_target_time_();
      pwmout_write(pwm, is_mark ? mark_duty : space_duty);
      this->target_time_ += is_mark ? uint32_t(item) : uint32_t(-item);
      App.feed_wdt();
    }
    this->await_target_time_();  // wait for duration of last pulse
    pwmout_write(pwm, space_duty);
    vTaskPrioritySet(nullptr, saved_priority);
    if (i + 1 < send_times) {
      // The repeat gap is user-configurable and unbounded, so wait it out at normal
      // priority, feeding the watchdog
      const uint32_t gap_end = micros() + send_wait;
      while ((int32_t) (gap_end - micros()) > 0) {
        App.feed_wdt();
      }
    }
  }
  this->complete_trigger_.trigger();
}

#endif  // USE_LIBRETINY_VARIANT_RTL8720C

}  // namespace esphome::remote_transmitter

#endif  // USE_RTL87XX && !CLANG_TIDY
