#ifdef TFLM_OPERATORS_ACTIVE

// TFLite Micro Operators Definition File
// Format:
//   TFLM_OP_AVAILABLE(BuiltinOperator_suffix, AddMethod)  -> operator exists in ESP32 TFLM library
//   TFLM_OP_UNAVAILABLE(BuiltinOperator_suffix)            -> operator not available, will be logged as unsupported

// ====== Core Neural Network Ops ======
TFLM_OP_AVAILABLE(CONV_2D, AddConv2D)
TFLM_OP_AVAILABLE(DEPTHWISE_CONV_2D, AddDepthwiseConv2D)
TFLM_OP_AVAILABLE(FULLY_CONNECTED, AddFullyConnected)
TFLM_OP_AVAILABLE(SOFTMAX, AddSoftmax)
TFLM_OP_AVAILABLE(AVERAGE_POOL_2D, AddAveragePool2D)
TFLM_OP_AVAILABLE(MAX_POOL_2D, AddMaxPool2D)
TFLM_OP_AVAILABLE(MEAN, AddMean)
TFLM_OP_AVAILABLE(L2_POOL_2D, AddL2Pool2D)
TFLM_OP_AVAILABLE(L2_NORMALIZATION, AddL2Normalization)

// ====== Activation Functions ======
TFLM_OP_AVAILABLE(RELU, AddRelu)
TFLM_OP_AVAILABLE(RELU6, AddRelu6)
TFLM_OP_UNAVAILABLE(RELU_N1_TO_1)
TFLM_OP_AVAILABLE(LOGISTIC, AddLogistic)
TFLM_OP_AVAILABLE(TANH, AddTanh)
TFLM_OP_AVAILABLE(HARD_SWISH, AddHardSwish)
TFLM_OP_AVAILABLE(LEAKY_RELU, AddLeakyRelu)
TFLM_OP_AVAILABLE(PRELU, AddPrelu)
TFLM_OP_AVAILABLE(LOG_SOFTMAX, AddLogSoftmax)
TFLM_OP_AVAILABLE(ELU, AddElu)

// ====== Basic Math Ops ======
TFLM_OP_AVAILABLE(ADD, AddAdd)
TFLM_OP_AVAILABLE(ADD_N, AddAddN)
TFLM_OP_AVAILABLE(SUB, AddSub)
TFLM_OP_AVAILABLE(MUL, AddMul)
TFLM_OP_AVAILABLE(DIV, AddDiv)
TFLM_OP_AVAILABLE(FLOOR_DIV, AddFloorDiv)
TFLM_OP_AVAILABLE(FLOOR_MOD, AddFloorMod)
TFLM_OP_AVAILABLE(FLOOR, AddFloor)
TFLM_OP_AVAILABLE(CEIL, AddCeil)
TFLM_OP_AVAILABLE(ROUND, AddRound)
TFLM_OP_AVAILABLE(ABS, AddAbs)
TFLM_OP_AVAILABLE(SQRT, AddSqrt)
TFLM_OP_AVAILABLE(RSQRT, AddRsqrt)
TFLM_OP_AVAILABLE(SQUARE, AddSquare)
TFLM_OP_AVAILABLE(SQUARED_DIFFERENCE, AddSquaredDifference)
TFLM_OP_UNAVAILABLE(POW)
TFLM_OP_AVAILABLE(EXP, AddExp)
TFLM_OP_AVAILABLE(LOG, AddLog)
TFLM_OP_AVAILABLE(SIN, AddSin)
TFLM_OP_AVAILABLE(COS, AddCos)
TFLM_OP_AVAILABLE(NEG, AddNeg)
TFLM_OP_AVAILABLE(CAST, AddCast)
TFLM_OP_AVAILABLE(CUMSUM, AddCumSum)

// ====== Comparison Ops ======
TFLM_OP_AVAILABLE(EQUAL, AddEqual)
TFLM_OP_AVAILABLE(NOT_EQUAL, AddNotEqual)
TFLM_OP_AVAILABLE(GREATER, AddGreater)
TFLM_OP_AVAILABLE(GREATER_EQUAL, AddGreaterEqual)
TFLM_OP_AVAILABLE(LESS, AddLess)
TFLM_OP_AVAILABLE(LESS_EQUAL, AddLessEqual)

// ====== Tensor Operations ======
TFLM_OP_AVAILABLE(RESHAPE, AddReshape)
TFLM_OP_AVAILABLE(SHAPE, AddShape)
TFLM_OP_AVAILABLE(QUANTIZE, AddQuantize)
TFLM_OP_AVAILABLE(DEQUANTIZE, AddDequantize)
TFLM_OP_AVAILABLE(CONCATENATION, AddConcatenation)
TFLM_OP_AVAILABLE(SPLIT, AddSplit)
TFLM_OP_AVAILABLE(SPLIT_V, AddSplitV)
TFLM_OP_AVAILABLE(STRIDED_SLICE, AddStridedSlice)
TFLM_OP_AVAILABLE(SLICE, AddSlice)
TFLM_OP_AVAILABLE(PACK, AddPack)
TFLM_OP_AVAILABLE(UNPACK, AddUnpack)
TFLM_OP_AVAILABLE(PAD, AddPad)
TFLM_OP_AVAILABLE(PADV2, AddPadV2)
TFLM_OP_AVAILABLE(MIRROR_PAD, AddMirrorPad)
TFLM_OP_AVAILABLE(FILL, AddFill)
TFLM_OP_AVAILABLE(EXPAND_DIMS, AddExpandDims)
TFLM_OP_AVAILABLE(SQUEEZE, AddSqueeze)
TFLM_OP_AVAILABLE(TRANSPOSE, AddTranspose)
TFLM_OP_AVAILABLE(TRANSPOSE_CONV, AddTransposeConv)
TFLM_OP_AVAILABLE(SPACE_TO_BATCH_ND, AddSpaceToBatchNd)
TFLM_OP_AVAILABLE(BATCH_TO_SPACE_ND, AddBatchToSpaceNd)
TFLM_OP_AVAILABLE(SPACE_TO_DEPTH, AddSpaceToDepth)
TFLM_OP_AVAILABLE(DEPTH_TO_SPACE, AddDepthToSpace)
TFLM_OP_AVAILABLE(BROADCAST_ARGS, AddBroadcastArgs)
TFLM_OP_AVAILABLE(BROADCAST_TO, AddBroadcastTo)
TFLM_OP_AVAILABLE(ZEROS_LIKE, AddZerosLike)

// ====== Reduction Ops ======
TFLM_OP_AVAILABLE(REDUCE_MAX, AddReduceMax)
TFLM_OP_AVAILABLE(REDUCE_MIN, AddReduceMin)
TFLM_OP_UNAVAILABLE(REDUCE_PROD)
TFLM_OP_AVAILABLE(SUM, AddSum)
TFLM_OP_UNAVAILABLE(REDUCE_ANY)
TFLM_OP_UNAVAILABLE(REDUCE_ALL)

// ====== Element-wise Ops ======
TFLM_OP_AVAILABLE(MAXIMUM, AddMaximum)
TFLM_OP_AVAILABLE(MINIMUM, AddMinimum)
TFLM_OP_AVAILABLE(ARG_MAX, AddArgMax)
TFLM_OP_AVAILABLE(ARG_MIN, AddArgMin)
TFLM_OP_UNAVAILABLE(SELECT)
TFLM_OP_AVAILABLE(SELECT_V2, AddSelectV2)

// ====== Logical Ops ======
TFLM_OP_AVAILABLE(LOGICAL_AND, AddLogicalAnd)
TFLM_OP_AVAILABLE(LOGICAL_OR, AddLogicalOr)
TFLM_OP_AVAILABLE(LOGICAL_NOT, AddLogicalNot)

// ====== Advanced Ops ======
TFLM_OP_AVAILABLE(RESIZE_NEAREST_NEIGHBOR, AddResizeNearestNeighbor)
TFLM_OP_AVAILABLE(RESIZE_BILINEAR, AddResizeBilinear)
TFLM_OP_AVAILABLE(GATHER, AddGather)
TFLM_OP_AVAILABLE(GATHER_ND, AddGatherNd)
TFLM_OP_UNAVAILABLE(WHERE)
TFLM_OP_UNAVAILABLE(REVERSE_SEQUENCE)
TFLM_OP_AVAILABLE(REVERSE_V2, AddReverseV2)
TFLM_OP_AVAILABLE(UNIDIRECTIONAL_SEQUENCE_LSTM, AddUnidirectionalSequenceLSTM)
TFLM_OP_UNAVAILABLE(BIDIRECTIONAL_SEQUENCE_LSTM)
TFLM_OP_UNAVAILABLE(BIDIRECTIONAL_SEQUENCE_RNN)

// ====== Quantization Ops ======
TFLM_OP_UNAVAILABLE(FAKE_QUANT)

// ====== Embedding Ops ======
TFLM_OP_AVAILABLE(EMBEDDING_LOOKUP, AddEmbeddingLookup)
TFLM_OP_UNAVAILABLE(EMBEDDING_LOOKUP_SPARSE)

// ====== Local Response Normalization ======
TFLM_OP_UNAVAILABLE(LOCAL_RESPONSE_NORMALIZATION)

// ====== Matrix Operations ======
TFLM_OP_AVAILABLE(BATCH_MATMUL, AddBatchMatMul)

// ====== Variable / Control Flow Ops ======
TFLM_OP_AVAILABLE(IF, AddIf)
TFLM_OP_AVAILABLE(WHILE, AddWhile)
TFLM_OP_AVAILABLE(CALL_ONCE, AddCallOnce)
TFLM_OP_AVAILABLE(ASSIGN_VARIABLE, AddAssignVariable)
TFLM_OP_AVAILABLE(READ_VARIABLE, AddReadVariable)
TFLM_OP_AVAILABLE(VAR_HANDLE, AddVarHandle)

// ====== Skip Ops (not available in TFLM, no Add method) ======
TFLM_OP_UNAVAILABLE(CUSTOM)
TFLM_OP_UNAVAILABLE(HASHTABLE_LOOKUP)
TFLM_OP_UNAVAILABLE(SVDF)
TFLM_OP_UNAVAILABLE(LSH_PROJECTION)
TFLM_OP_UNAVAILABLE(SKIP_GRAM)
TFLM_OP_UNAVAILABLE(CALL)

#endif  // TFLM_OPERATORS_ACTIVE
