#pragma once

#include "esphome/components/i2c/i2c.h"
#include "esphome/components/touchscreen/touchscreen.h"
#include "esphome/core/component.h"
#include "esphome/core/hal.h"
#include "esphome/core/log.h"

namespace esphome {
namespace gsl3670 {

static const char *const TAG = "gsl3670.touchscreen";
// ---------------------------------------------------------------------------
// Firmware record format
// Matches `struct fw_data` in the Seeed BSP header:
//   char    offset;   -- register offset within the current page,
//                        OR 0xf0 to select a new page
//   uint32_t val;     -- 32-bit value to write (little-endian, 4 bytes)
//
// When offset == 0xf0 the driver writes only the low byte of val to reg 0xf0
// (page select).  All other offsets write all 4 bytes to (page<<7)|offset.
// ---------------------------------------------------------------------------
struct GSL3670FwRecord {
  uint8_t offset;  ///< Register offset, or 0xf0 = page-select
  uint32_t val;    ///< Value to write
};

// ---------------------------------------------------------------------------
// GSL3670 touchscreen ESPHome component
// ---------------------------------------------------------------------------
class GSL3670Touchscreen : public touchscreen::Touchscreen, public i2c::I2CDevice {
 public:
  /// Supply the firmware table (generated by codegen from the YAML)
  void set_firmware(const GSL3670FwRecord *fw, size_t len) {
    firmware_ = fw;
    firmware_len_ = len;
  }

  /// Supply the config blob for gsl_DataInit (the gsl_config_data_id array)
  void set_config(const uint32_t *cfg, size_t len) {
    config_ = cfg;
    config_len_ = len;
  }

  void set_interrupt_pin(InternalGPIOPin *pin) { interrupt_pin_ = pin; }
  void set_reset_pin(GPIOPin *pin) { reset_pin_ = pin; }

  // touchscreen::Touchscreen / Component interface
  void setup() override;
  void dump_config() override;

 protected:
  void update_touches() override;

 private:
  // ---------- init steps (mirrors esp_lcd_touch_gsl3670_init) ----------
  void clear_reg_();      // GPIO reset + 0x88/0xe4/0xe0 sequence
  void reset_();          // GPIO reset + 0xe4/0xbc sequence
  void load_firmware_();  // write GSLX670_FW table
  void startup_chip_();   // 0x00→0xe0 + gsl_DataInit

  // ---------- I2C helpers ----------
  bool write_reg_(uint8_t reg, const uint8_t *data, size_t len);
  bool write_reg32_(uint8_t reg, uint32_t val);  // writes 4 bytes LE
  bool write_reg8_(uint8_t reg, uint8_t val);
  bool read_reg_(uint8_t reg, uint8_t *data, size_t len);

  InternalGPIOPin *interrupt_pin_{nullptr};
  GPIOPin *reset_pin_{nullptr};

  const GSL3670FwRecord *firmware_{nullptr};
  size_t firmware_len_{0};

  const uint32_t *config_{nullptr};
  size_t config_len_{0};
};

}  // namespace gsl3670
}  // namespace esphome
