dependencies:
  espressif/esp-sr:
    version: ^2.4.6
  espressif/gmf_core:
    require: public
    version: ^1.0
description: Espressif GMF AI Audio Elements Module
documentation: https://github.com/espressif/esp-gmf/blob/main/elements/gmf_ai_audio/README.md
issues: https://github.com/espressif/esp-gmf/issues
repository: git://github.com/espressif/esp-gmf.git
repository_info:
  commit_sha: 5d8134be49b5cfeb96781f851ae76660dfa5868d
  path: ./elements/gmf_ai_audio
tags:
  - gmf
url: https://github.com/espressif/esp-gmf/tree/main/elements/gmf_ai_audio
version: 1.0.0~1
