"""The parts of a ``build.ninja`` every native backend emits the same way.

Rule names match ``SOURCE_KIND_FOR_SUFFIX`` values (c, cxx, asm, aspp) and
``ninja.COMPILE_RULES``, which the compile database is asked for.
"""

from __future__ import annotations

from collections.abc import Collection, Sequence
import logging
import os
from pathlib import Path
import sys
from typing import TYPE_CHECKING

from esphome.build_helpers.idedata import is_joined_include
from esphome.build_helpers.ninja import (
    escape as _e,
    quote_path as _q,
    shell_token as _shell_token,
)
from esphome.build_helpers.pch import (
    PCH_GCH_NAME,
    PCH_SUM_NAME,
    log_pch_in_use,
    pch_consumer_flags,
    pch_enabled,
    pch_identity,
    write_pch_headers,
)
from esphome.framework_helpers import strip_win_long_path_prefix
from esphome.helpers import write_file_if_changed
from esphome.platformio.library import SOURCE_KIND_FOR_SUFFIX

if TYPE_CHECKING:
    from esphome.arduino.library import ArduinoLibrary

_LOGGER = logging.getLogger(__name__)

_BUILD_TOOL = Path(__file__).parent.parent / "build_gen" / "build_tool.py"


def collect_sources(root: Path, exclude: Collection[str] = frozenset()) -> list[Path]:
    return sorted(
        p
        for p in root.rglob("*")
        if p.suffix in SOURCE_KIND_FOR_SUFFIX and p.name not in exclude
    )


def common_parent(paths: list[Path]) -> Path:
    return Path(os.path.commonpath([str(p.parent) for p in paths]))


def _command(words: Sequence[Path | str]) -> str:
    program, *args = words
    return " ".join([_q(program), *(_shell_token(str(a)) for a in args)])


def tool_lines(
    cc: Sequence[Path | str], cxx: Sequence[Path | str], ccache: str | None
) -> list[str]:
    """The file header: the compilers and the helper tools as variables.

    A compiler is its program followed by any arguments it always takes.
    """
    return [
        "# Auto-generated by ESPHome",
        "ninja_required_version = 1.5",
        f"cc = {_command(cc)}",
        f"cxx = {_command(cxx)}",
        # The NSIS launcher starts Python with a \\?\ extended-length path
        # that cmd.exe cannot spawn; same strip every other emitted binary
        # path gets
        f"python = {_q(strip_win_long_path_prefix(sys.executable))}",
        f"buildtool = {_q(_BUILD_TOOL)}",
        f"ccache = {_q(ccache) if ccache else ''}",
        "",
    ]


def compile_rule_lines() -> list[str]:
    """The compile rules; ``$own_includes`` is empty unless an edge sets it."""
    return [
        "rule c",
        "  command = $ccache $cc -MMD -MF $out.d $own_includes $cflags $flags -c $in -o $out",
        "  depfile = $out.d",
        "  deps = gcc",
        "  description = CC $out",
        "rule cxx",
        "  command = $ccache $cxx -MMD -MF $out.d $own_includes $cxxflags $flags -c $in -o $out",
        "  depfile = $out.d",
        "  deps = gcc",
        "  description = CXX $out",
        "rule aspp",
        "  command = $ccache $cc -MMD -MF $out.d -x assembler-with-cpp $own_includes $asflags $flags -c $in -o $out",
        "  depfile = $out.d",
        "  deps = gcc",
        "  description = AS $out",
        # Plain assembler, as SCons's ASCOM: no preprocessor, so no
        # depfile and no $flags (defines/includes) either
        "rule asm",
        "  command = $ccache $cc -x assembler $asflags -c $in -o $out",
        "  description = AS $out",
    ]


def pch_rule_lines() -> list[str]:
    """The precompiled header rule, for a generator that emits one."""
    return [
        # No $ccache: the .gch embeds build dir paths
        "rule pch",
        "  command = $cxx -MMD -MF $out.d -x c++-header $cxxflags $flags -c $in -o $out",
        "  depfile = $out.d",
        "  deps = gcc",
        "  description = PCH $out",
    ]


def pch_edges(
    lines: list[str],
    build_dir: Path,
    src_dir: Path,
    headers: Sequence[str],
    cxxflags: Sequence[str],
    src_flags: Sequence[str],
    identity: Sequence[str],
) -> tuple[str, str] | None:
    """Emit the precompiled header for the C++ src edges.

    ``headers`` are folded into one prefix header, ``src_flags`` are the
    flags every src edge carries and ``identity`` names what else the
    compile depends on, the compiler included. Returns the ``cxx_override``
    for ``compile_edges``, or None without a pch.
    """
    if not pch_enabled():
        return None
    if any(
        tok == "-include" or tok.startswith("--include") or is_joined_include(tok)
        for tok in cxxflags
    ):
        # $cxxflags expands first and GCC only loads a .gch for the first
        # -include
        _LOGGER.warning(
            "A -include in build_flags prevents the precompiled header from "
            "loading; compiling without it"
        )
        return None
    log_pch_in_use()
    source = write_pch_headers(build_dir, headers)
    write_file_if_changed(
        build_dir / PCH_SUM_NAME,
        pch_identity([*cxxflags, *src_flags], src_dir, tuple(headers), identity) + "\n",
    )
    gch = _e(PCH_GCH_NAME)
    # The checksum file changes with anything the .gch depends on
    lines.append(f"build {gch}: pch {_e(source)} | {_e(PCH_SUM_NAME)}")
    if src_flags:
        lines.append(f"  flags = {' '.join(src_flags)}")
    lines.append(f"srccxxflags = {' '.join([*src_flags, *pch_consumer_flags()])}")
    return ("$srccxxflags", gch)


def ar_rule_lines(ar: Path | str) -> list[str]:
    return [
        "rule ar",
        f"  command = $python $buildtool ar {_q(ar)} $out $out.rsp",
        "  rspfile = $out.rsp",
        "  rspfile_content = $in_newline",
        "  description = AR $out",
    ]


def compile_edges(
    lines: list[str],
    sources: list[Path],
    root: Path,
    group: str,
    flags: str = "",
    own_includes: str = "",
    cxx_override: tuple[str, str] | None = None,
) -> list[str]:
    """Emit compile edges for ``sources``; return the object paths.

    ``cxx_override`` is a (flags, implicit-dep) pair applied to C++ edges
    only, replacing ``flags`` (used for the precompiled header).
    """
    objects = []
    for src in sources:
        rel = src.relative_to(root).as_posix()
        obj = f"obj/{group}/{rel}.o"
        escaped_obj = _e(obj)
        kind = SOURCE_KIND_FOR_SUFFIX[src.suffix]
        override = cxx_override if kind == "cxx" else None
        implicit = f" | {override[1]}" if override else ""
        lines.append(f"build {escaped_obj}: {kind} {_e(src)}{implicit}")
        if own_includes:
            lines.append(f"  own_includes = {own_includes}")
        if edge_flags := override[0] if override else flags:
            lines.append(f"  flags = {edge_flags}")
        # Escaped once here: the returned paths only ever appear in build
        # statements (archive/link inputs), which use ninja escaping
        objects.append(escaped_obj)
    return objects


def library_edges(
    lines: list[str], libraries: list[ArduinoLibrary]
) -> tuple[list[str], list[str]]:
    """Emit every library's compile and archive edges.

    Returns the archive names and the objects that link directly. A
    library's own include dirs lead its compile lines, as PlatformIO searched
    them first: the include path is one global list, so another library's
    header of the same name would shadow them.
    """
    archives: list[str] = []
    direct_objs: list[str] = []
    for lib in libraries:
        if not lib.sources:
            # Header-only libraries are legitimate; the log makes an empty
            # srcFilter or broken tree traceable before link errors do
            _LOGGER.debug(
                "Library %s has no source files; contributing includes only",
                lib.name,
            )
            continue
        objs = compile_edges(
            lines,
            lib.sources,
            common_parent(lib.sources),
            f"lib/{lib.name}",
            flags=" ".join(_shell_token(f) for f in lib.flags),
            own_includes=" ".join(f"-I{_q(d)}" for d in lib.include_dirs),
        )
        if not lib.lib_archive:
            # libArchive: false / dot_a_linkage=false: hand the objects to
            # the linker directly so unreferenced-but-required symbols
            # (exception handlers, weak overrides) survive
            direct_objs.extend(objs)
            continue
        archive = f"lib{lib.name}.a"
        lines.append(f"build {_e(archive)}: ar {' '.join(objs)}")
        archives.append(archive)
    return archives, direct_objs


# One build flag: the flag, plus its argument when that is a separate token
Flag = tuple[str, ...]

# Flags whose path operand is the next token; gcc also takes it glued on
PATH_ARG_FLAGS = ("-include", "-imacros", "-isystem", "-iquote", "-idirafter")
# Flags whose path operand is glued on
PATH_PREFIXES = ("-I", "-L", *PATH_ARG_FLAGS)


def _anchor(path: str, base: Path) -> str:
    if not path or Path(path).is_absolute():
        return path
    return str(base / path)


def anchor_path_flag(flag: Flag, base: Path) -> Flag:
    """Anchor a flag's relative path operand at ``base``.

    PlatformIO ran the compiler from the build path; ninja runs it from
    ``.pioenvs/<name>``, where a relative operand would point elsewhere.
    """
    name, *args = flag
    if args:
        if name in PATH_ARG_FLAGS:
            return (name, _anchor(args[0], base))
        return flag
    for prefix in PATH_PREFIXES:
        if name.startswith(prefix):
            return (prefix + _anchor(name[len(prefix) :], base),)
    return flag
