"""The parts of a ``build.ninja`` every native backend emits the same way.

Rule names match ``SOURCE_KIND_FOR_SUFFIX`` values (c, cxx, asm, aspp) and
``ninja.COMPILE_RULES``, which the compile database is asked for.
"""

from __future__ import annotations

from collections.abc import Collection, Sequence
import logging
import os
from pathlib import Path
import sys
from typing import TYPE_CHECKING

from esphome.build_helpers.ccache import effective_ccache_basedir
from esphome.build_helpers.ninja import (
    escape as _e,
    quote_path as _q,
    shell_token as _shell_token,
)
from esphome.build_helpers.pch import (
    PCH_HEADER_NAME,
    mark_pch_emitted,
    pch_checksum,
    pch_consumer_escalation,
    pch_degraded,
    pch_disabled_degraded,
    pch_enabled,
    pch_header_text,
    pch_probe_args,
    pch_strict,
)
from esphome.core import CORE
from esphome.framework_helpers import strip_win_long_path_prefix
from esphome.helpers import write_file_if_changed
from esphome.platformio.library import SOURCE_KIND_FOR_SUFFIX

if TYPE_CHECKING:
    from esphome.arduino.library import ArduinoLibrary

_LOGGER = logging.getLogger(__name__)

_BUILD_TOOL = Path(__file__).parent.parent / "build_gen" / "build_tool.py"


def collect_sources(root: Path, exclude: Collection[str] = frozenset()) -> list[Path]:
    return sorted(
        p
        for p in root.rglob("*")
        if p.suffix in SOURCE_KIND_FOR_SUFFIX and p.name not in exclude
    )


def common_parent(paths: list[Path]) -> Path:
    return Path(os.path.commonpath([str(p.parent) for p in paths]))


def _command(words: Sequence[Path | str]) -> str:
    program, *args = words
    return " ".join([_q(program), *(_shell_token(str(a)) for a in args)])


def tool_lines(
    cc: Sequence[Path | str], cxx: Sequence[Path | str], ccache: str | None
) -> list[str]:
    """The file header: the compilers and the helper tools as variables.

    A compiler is its program followed by any arguments it always takes.
    """
    return [
        "# Auto-generated by ESPHome",
        "ninja_required_version = 1.5",
        f"cc = {_command(cc)}",
        f"cxx = {_command(cxx)}",
        # The NSIS launcher starts Python with a \\?\ extended-length path
        # that cmd.exe cannot spawn; same strip every other emitted binary
        # path gets
        f"python = {_q(strip_win_long_path_prefix(sys.executable))}",
        f"buildtool = {_q(_BUILD_TOOL)}",
        f"ccache = {_q(ccache) if ccache else ''}",
        "",
    ]


def compile_rule_lines() -> list[str]:
    """The compile rules; ``$own_includes`` is empty unless an edge sets it."""
    return [
        "rule c",
        "  command = $ccache $cc -MMD -MF $out.d $own_includes $cflags $flags -c $in -o $out",
        "  depfile = $out.d",
        "  deps = gcc",
        "  description = CC $out",
        "rule cxx",
        "  command = $ccache $cxx -MMD -MF $out.d $own_includes $cxxflags $flags -c $in -o $out",
        "  depfile = $out.d",
        "  deps = gcc",
        "  description = CXX $out",
        "rule aspp",
        "  command = $ccache $cc -MMD -MF $out.d -x assembler-with-cpp $own_includes $asflags $flags -c $in -o $out",
        "  depfile = $out.d",
        "  deps = gcc",
        "  description = AS $out",
        # Plain assembler, as SCons's ASCOM: no preprocessor, so no
        # depfile and no $flags (defines/includes) either
        "rule asm",
        "  command = $ccache $cc -x assembler $asflags -c $in -o $out",
        "  description = AS $out",
    ]


def pch_rule_lines() -> list[str]:
    """The precompiled header rule, for a generator that emits one."""
    return [
        # No $ccache: the .gch is compiled once per build dir and ccache
        # cannot cache it usefully (its bytes embed build-dir paths)
        "rule pch",
        "  command = $cxx -MMD -MF $out.d -x c++-header $cxxflags $flags -c $in -o $out",
        "  depfile = $out.d",
        "  deps = gcc",
        "  description = PCH $out",
    ]


def pch_edges(
    lines: list[str],
    build_dir: Path,
    src_dir: Path,
    headers: Sequence[str],
    cxxflags: Sequence[str],
    src_flags: Sequence[str],
    ccache: str | None,
    identity: Sequence[str],
) -> tuple[str, str] | None:
    """Emit the precompiled header for the C++ src edges.

    ``headers`` are folded into one prefix header, ``src_flags`` are the
    flags every src edge carries, and ``identity`` names what the compile
    depends on beyond the headers and flags (versioned install paths).
    Returns the ``cxx_override`` for ``compile_edges``, or None when the
    build goes without a precompiled header.
    """
    if not pch_enabled():
        pch_disabled_degraded()
        return None
    if any(tok.startswith("-include") for tok in cxxflags):
        # $cxxflags expands first, so a user -include there means GCC would
        # never load the .gch
        _LOGGER.warning(
            "A -include in build_flags prevents the precompiled header from "
            "loading; compiling without it"
        )
        pch_degraded("a user -include precedes the pch")
        return None
    pch_header = build_dir / PCH_HEADER_NAME
    pch_text = pch_header_text(headers)
    checksum = None
    try:
        if ccache:
            # The .sum exists only for CCACHE_PCH_EXTSUM; ninja's depfile
            # handles staleness. Strip resolved and raw build paths
            # (symlinks) so identical configs share cache entries
            flags_id = (
                " ".join(cxxflags)
                .replace(effective_ccache_basedir(), "")
                .replace(str(CORE.build_path), "")
            )
            # The header text covers include order
            checksum = pch_checksum(src_dir, headers, (pch_text, *identity, flags_id))
    except (OSError, UnicodeError) as err:
        # Identity unknown: a stale cache entry must never be served
        _LOGGER.warning(
            "Could not establish the pch identity; compiling without it: %s", err
        )
        pch_degraded(f"identity unknown: {err}")
        return None
    _LOGGER.info(
        "Compiling with a precompiled header (set ESPHOME_PCH_ENABLE=0 to disable)"
    )
    write_file_if_changed(pch_header, pch_text)
    sum_path = build_dir / f"{PCH_HEADER_NAME}.gch.sum"
    if checksum is not None:
        # Generate-time stamp: a hand-run ninja can rebuild the .gch
        # while this .sum lags
        write_file_if_changed(sum_path, checksum + "\n")
    else:
        # A stale .sum from an earlier ccache run must not survive
        sum_path.unlink(missing_ok=True)
    gch = _e(f"{PCH_HEADER_NAME}.gch")
    lines.append(f"build {gch}: pch {_e(pch_header)}")
    if src_flags:
        lines.append(f"  flags = {' '.join(src_flags)}")
    # Relative -include: absolute would break cross-device ccache.
    # -Wno-error keeps a rejected .gch a warning under user -Werror;
    # strict inverts it so any consumer rejection reds the build
    # (rejection is per-process, so the probe alone cannot prove
    # the consumers)
    cxx_parts = [
        *src_flags,
        f"-Winvalid-pch {pch_consumer_escalation()} -include {PCH_HEADER_NAME}",
    ]
    lines.append(f"srccxxflags = {' '.join(cxx_parts)}")
    pch_dep = gch
    if pch_strict():
        # Consumers wait on the probe stamp, so an unloadable .gch
        # reds the build here instead of warning ~100 times
        probe = " ".join(pch_probe_args(PCH_HEADER_NAME, source=os.devnull))
        lines.append("rule pchprobe")
        # $out only expands in rule text, hence the inline stamp
        lines.append(
            f"  command = $cxx $cxxflags $flags {probe}"
            " && $python $buildtool touch $out"
        )
        lines.append("  description = PCHPROBE $out")
        # Runs when the .gch is (re)built; strict consumer -Werror
        # covers a cached .gch this process cannot load
        lines.append(f"build esphome_pch.probe: pchprobe {gch}")
        if src_flags:
            lines.append(f"  flags = {' '.join(src_flags)}")
        pch_dep = f"{gch} esphome_pch.probe"
    mark_pch_emitted()
    return ("$srccxxflags", pch_dep)


def ar_rule_lines(ar: Path | str) -> list[str]:
    return [
        "rule ar",
        f"  command = $python $buildtool ar {_q(ar)} $out $out.rsp",
        "  rspfile = $out.rsp",
        "  rspfile_content = $in_newline",
        "  description = AR $out",
    ]


def compile_edges(
    lines: list[str],
    sources: list[Path],
    root: Path,
    group: str,
    flags: str = "",
    own_includes: str = "",
    cxx_override: tuple[str, str] | None = None,
) -> list[str]:
    """Emit compile edges for ``sources``; return the object paths.

    ``cxx_override`` is a (flags, implicit-dep) pair applied to C++ edges
    only, replacing ``flags`` (used for the precompiled header).
    """
    objects = []
    for src in sources:
        rel = src.relative_to(root).as_posix()
        obj = f"obj/{group}/{rel}.o"
        escaped_obj = _e(obj)
        kind = SOURCE_KIND_FOR_SUFFIX[src.suffix]
        override = cxx_override if kind == "cxx" else None
        implicit = f" | {override[1]}" if override else ""
        lines.append(f"build {escaped_obj}: {kind} {_e(src)}{implicit}")
        if own_includes:
            lines.append(f"  own_includes = {own_includes}")
        if edge_flags := override[0] if override else flags:
            lines.append(f"  flags = {edge_flags}")
        # Escaped once here: the returned paths only ever appear in build
        # statements (archive/link inputs), which use ninja escaping
        objects.append(escaped_obj)
    return objects


def library_edges(
    lines: list[str], libraries: list[ArduinoLibrary]
) -> tuple[list[str], list[str]]:
    """Emit every library's compile and archive edges.

    Returns the archive names and the objects that link directly. A
    library's own include dirs lead its compile lines, as PlatformIO searched
    them first: the include path is one global list, so another library's
    header of the same name would shadow them.
    """
    archives: list[str] = []
    direct_objs: list[str] = []
    for lib in libraries:
        if not lib.sources:
            # Header-only libraries are legitimate; the log makes an empty
            # srcFilter or broken tree traceable before link errors do
            _LOGGER.debug(
                "Library %s has no source files; contributing includes only",
                lib.name,
            )
            continue
        objs = compile_edges(
            lines,
            lib.sources,
            common_parent(lib.sources),
            f"lib/{lib.name}",
            flags=" ".join(_shell_token(f) for f in lib.flags),
            own_includes=" ".join(f"-I{_q(d)}" for d in lib.include_dirs),
        )
        if not lib.lib_archive:
            # libArchive: false / dot_a_linkage=false: hand the objects to
            # the linker directly so unreferenced-but-required symbols
            # (exception handlers, weak overrides) survive
            direct_objs.extend(objs)
            continue
        archive = f"lib{lib.name}.a"
        lines.append(f"build {_e(archive)}: ar {' '.join(objs)}")
        archives.append(archive)
    return archives, direct_objs


# One build flag: the flag, plus its argument when that is a separate token
Flag = tuple[str, ...]

# Flags whose path operand is the next token; gcc also takes it glued on
PATH_ARG_FLAGS = ("-include", "-imacros", "-isystem", "-iquote", "-idirafter")
# Flags whose path operand is glued on
PATH_PREFIXES = ("-I", "-L", *PATH_ARG_FLAGS)


def _anchor(path: str, base: Path) -> str:
    if not path or Path(path).is_absolute():
        return path
    return str(base / path)


def anchor_path_flag(flag: Flag, base: Path) -> Flag:
    """Anchor a flag's relative path operand at ``base``.

    PlatformIO ran the compiler from the build path; ninja runs it from
    ``.pioenvs/<name>``, where a relative operand would point elsewhere.
    """
    name, *args = flag
    if args:
        if name in PATH_ARG_FLAGS:
            return (name, _anchor(args[0], base))
        return flag
    for prefix in PATH_PREFIXES:
        if name.startswith(prefix):
            return (prefix + _anchor(name[len(prefix) :], base),)
    return flag
