"""The parts of a ``build.ninja`` every native backend emits the same way.

Rule names match ``SOURCE_KIND_FOR_SUFFIX`` values (c, cxx, asm, aspp) and
``ninja.COMPILE_RULES``, which the compile database is asked for.
"""

from __future__ import annotations

from collections.abc import Collection, Sequence
import logging
import os
from pathlib import Path
import sys
from typing import TYPE_CHECKING

from esphome.build_helpers.ninja import (
    escape as _e,
    quote_path as _q,
    shell_token as _shell_token,
)
from esphome.framework_helpers import strip_win_long_path_prefix
from esphome.platformio.library import SOURCE_KIND_FOR_SUFFIX

if TYPE_CHECKING:
    from esphome.arduino.library import ArduinoLibrary

_LOGGER = logging.getLogger(__name__)

_BUILD_TOOL = Path(__file__).parent.parent / "build_gen" / "build_tool.py"


def collect_sources(root: Path, exclude: Collection[str] = frozenset()) -> list[Path]:
    return sorted(
        p
        for p in root.rglob("*")
        if p.suffix in SOURCE_KIND_FOR_SUFFIX and p.name not in exclude
    )


def common_parent(paths: list[Path]) -> Path:
    return Path(os.path.commonpath([str(p.parent) for p in paths]))


def _command(words: Sequence[Path | str]) -> str:
    program, *args = words
    return " ".join([_q(program), *(_shell_token(str(a)) for a in args)])


def tool_lines(
    cc: Sequence[Path | str], cxx: Sequence[Path | str], ccache: str | None
) -> list[str]:
    """The file header: the compilers and the helper tools as variables.

    A compiler is its program followed by any arguments it always takes.
    """
    return [
        "# Auto-generated by ESPHome",
        "ninja_required_version = 1.5",
        f"cc = {_command(cc)}",
        f"cxx = {_command(cxx)}",
        # The NSIS launcher starts Python with a \\?\ extended-length path
        # that cmd.exe cannot spawn; same strip every other emitted binary
        # path gets
        f"python = {_q(strip_win_long_path_prefix(sys.executable))}",
        f"buildtool = {_q(_BUILD_TOOL)}",
        f"ccache = {_q(ccache) if ccache else ''}",
        "",
    ]


def compile_rule_lines() -> list[str]:
    """The compile rules; ``$own_includes`` is empty unless an edge sets it."""
    return [
        "rule c",
        "  command = $ccache $cc -MMD -MF $out.d $own_includes $cflags $flags -c $in -o $out",
        "  depfile = $out.d",
        "  deps = gcc",
        "  description = CC $out",
        "rule cxx",
        "  command = $ccache $cxx -MMD -MF $out.d $own_includes $cxxflags $flags -c $in -o $out",
        "  depfile = $out.d",
        "  deps = gcc",
        "  description = CXX $out",
        "rule aspp",
        "  command = $ccache $cc -MMD -MF $out.d -x assembler-with-cpp $own_includes $asflags $flags -c $in -o $out",
        "  depfile = $out.d",
        "  deps = gcc",
        "  description = AS $out",
        # Plain assembler, as SCons's ASCOM: no preprocessor, so no
        # depfile and no $flags (defines/includes) either
        "rule asm",
        "  command = $ccache $cc -x assembler $asflags -c $in -o $out",
        "  description = AS $out",
    ]


def ar_rule_lines(ar: Path | str) -> list[str]:
    return [
        "rule ar",
        f"  command = $python $buildtool ar {_q(ar)} $out $out.rsp",
        "  rspfile = $out.rsp",
        "  rspfile_content = $in_newline",
        "  description = AR $out",
    ]


def compile_edges(
    lines: list[str],
    sources: list[Path],
    root: Path,
    group: str,
    flags: str = "",
    own_includes: str = "",
) -> list[str]:
    """Emit compile edges for ``sources``; return the object paths."""
    objects = []
    for src in sources:
        rel = src.relative_to(root).as_posix()
        obj = f"obj/{group}/{rel}.o"
        escaped_obj = _e(obj)
        lines.append(
            f"build {escaped_obj}: {SOURCE_KIND_FOR_SUFFIX[src.suffix]} {_e(src)}"
        )
        if own_includes:
            lines.append(f"  own_includes = {own_includes}")
        if flags:
            lines.append(f"  flags = {flags}")
        # Escaped once here: the returned paths only ever appear in build
        # statements (archive/link inputs), which use ninja escaping
        objects.append(escaped_obj)
    return objects


def library_edges(
    lines: list[str], libraries: list[ArduinoLibrary]
) -> tuple[list[str], list[str]]:
    """Emit every library's compile and archive edges.

    Returns the archive names and the objects that link directly. A
    library's own include dirs lead its compile lines, as PlatformIO searched
    them first: the include path is one global list, so another library's
    header of the same name would shadow them.
    """
    archives: list[str] = []
    direct_objs: list[str] = []
    for lib in libraries:
        if not lib.sources:
            # Header-only libraries are legitimate; the log makes an empty
            # srcFilter or broken tree traceable before link errors do
            _LOGGER.debug(
                "Library %s has no source files; contributing includes only",
                lib.name,
            )
            continue
        objs = compile_edges(
            lines,
            lib.sources,
            common_parent(lib.sources),
            f"lib/{lib.name}",
            flags=" ".join(_shell_token(f) for f in lib.flags),
            own_includes=" ".join(f"-I{_q(d)}" for d in lib.include_dirs),
        )
        if not lib.lib_archive:
            # libArchive: false / dot_a_linkage=false: hand the objects to
            # the linker directly so unreferenced-but-required symbols
            # (exception handlers, weak overrides) survive
            direct_objs.extend(objs)
            continue
        archive = f"lib{lib.name}.a"
        lines.append(f"build {_e(archive)}: ar {' '.join(objs)}")
        archives.append(archive)
    return archives, direct_objs


# One build flag: the flag, plus its argument when that is a separate token
Flag = tuple[str, ...]

# Flags whose path operand is the next token; gcc also takes it glued on
PATH_ARG_FLAGS = ("-include", "-imacros", "-isystem", "-iquote", "-idirafter")
# Flags whose path operand is glued on
PATH_PREFIXES = ("-I", "-L", *PATH_ARG_FLAGS)


def _anchor(path: str, base: Path) -> str:
    if not path or Path(path).is_absolute():
        return path
    return str(base / path)


def anchor_path_flag(flag: Flag, base: Path) -> Flag:
    """Anchor a flag's relative path operand at ``base``.

    PlatformIO ran the compiler from the build path; ninja runs it from
    ``.pioenvs/<name>``, where a relative operand would point elsewhere.
    """
    name, *args = flag
    if args:
        if name in PATH_ARG_FLAGS:
            return (name, _anchor(args[0], base))
        return flag
    for prefix in PATH_PREFIXES:
        if name.startswith(prefix):
            return (prefix + _anchor(name[len(prefix) :], base),)
    return flag
