#pragma once

#include "uart.h"
#include "esphome/core/automation.h"

#include <vector>

namespace esphome {
namespace uart {

template<typename... Ts> class UARTWriteAction : public Action<Ts...>, public Parented<UARTComponent> {
 public:
  void set_data_template(std::vector<uint8_t> (*func)(Ts...)) {
    // Stateless lambdas (generated by ESPHome) implicitly convert to function pointers
    this->data_.func = func;
    this->static_ = false;
  }

  // Store pointer to static data in flash (no RAM copy)
  void set_data_static(const uint8_t *data, size_t len) {
    // Simply set pointer and length - no construction needed for POD types
    this->data_.static_data.ptr = data;
    this->data_.static_data.len = len;
    this->static_ = true;
  }

  void play(const Ts &...x) override {
    if (this->static_) {
      this->parent_->write_array(this->data_.static_data.ptr, this->data_.static_data.len);
    } else {
      auto val = this->data_.func(x...);
      this->parent_->write_array(val);
    }
  }

 protected:
  bool static_{true};  // Default to static mode (most common case)
  union Data {
    std::vector<uint8_t> (*func)(Ts...);  // Function pointer (stateless lambdas)
    struct {
      const uint8_t *ptr;
      size_t len;
    } static_data;
  } data_;
};

}  // namespace uart
}  // namespace esphome
