"""Component alias registry.

Generated by script/build_alias_registry.py - do not edit manually.
See the component-alias section of esphome/loader.py.
"""

# alias -> (canonical component, removal version or None)
COMPONENT_ALIASES: dict[str, tuple[str, str | None]] = {
    "rp2040": ("rp2", "2027.7.0"),
}
