dependencies:
  bblanchon/arduinojson:
    version: "7.4.2"
  esphome/esp-audio-libs:
    version: 2.0.4
  esphome/esp-micro-speech-features:
    version: 1.2.3
  esphome/micro-decoder:
    version: 0.2.0
  esphome/micro-flac:
    version: 0.1.1
  esphome/micro-mp3:
    version: 0.2.0
  esphome/micro-opus:
    version: 0.4.1
  espressif/esp-dsp:
    version: "1.7.1"
  espressif/esp-tflite-micro:
    version: 1.3.3~1
  espressif/esp32-camera:
    version: 2.1.6
  espressif/mdns:
    version: 1.11.0
  espressif/esp_wifi_remote:
    version: 1.5.1
    rules:
      - if: "target in [esp32h2, esp32p4]"
  espressif/wifi_remote_over_eppp:
    version: 0.3.2
    rules:
      - if: "target in [esp32h2, esp32p4]"
  espressif/eppp_link:
    version: 1.1.5
    rules:
      - if: "target in [esp32h2, esp32p4]"
  espressif/esp_hosted:
    version: 2.12.6
    rules:
      - if: "target in [esp32h2, esp32p4]"
  zorxx/multipart-parser:
    version: 1.0.1
  espressif/lan867x:
    version: "2.0.0"
    rules:
      - if: "target in [esp32, esp32p4]"
  espressif/esp-zboss-lib:
    version: 1.6.4
    rules:
      - if: "target in [esp32h2, esp32c5, esp32c6]"
  espressif/esp-zigbee-lib:
    version: 1.6.8
    rules:
      - if: "target in [esp32h2, esp32c5, esp32c6]"
  espressif/lan87xx:
    version: "1.0.0"
    rules:
      - if: "idf_version >=6.0.0 && target in [esp32, esp32p4]"
  espressif/rtl8201:
    version: "1.0.1"
    rules:
      - if: "idf_version >=6.0.0 && target in [esp32, esp32p4]"
  espressif/dp83848:
    version: "1.0.0"
    rules:
      - if: "idf_version >=6.0.0 && target in [esp32, esp32p4]"
  espressif/ip101:
    version: "1.0.0"
    rules:
      - if: "idf_version >=6.0.0 && target in [esp32, esp32p4]"
  espressif/ksz80xx:
    version: "1.0.0"
    rules:
      - if: "idf_version >=6.0.0 && target in [esp32, esp32p4]"
  espressif/w5500:
    version: "1.0.1"
    rules:
      - if: "idf_version >=6.0.0"
  espressif/dm9051:
    version: "1.0.0"
    rules:
      - if: "idf_version >=6.0.0"
  espressif/esp_tinyusb:
    version: "2.1.1"
    rules:
      - if: "target in [esp32s2, esp32s3, esp32p4]"
  esphome/esp-hub75:
    version: 0.3.5
    rules:
      - if: "target in [esp32, esp32s2, esp32s3, esp32c6, esp32p4]"
  espressif/mqtt:
    version: "1.0.0"
    rules:
      - if: "idf_version >=6.0.0"
  espressif/usb:
    version: "1.3.0"
    rules:
      - if: "idf_version >=6.0.0 && target in [esp32s2, esp32s3, esp32p4]"
  esp32async/asynctcp:
    version: 3.4.91
  sendspin/sendspin-cpp:
    version: 0.4.0
  lvgl/lvgl:
    version: 9.5.0
