CONF_ENABLED = "enabled"
CONF_REGISTER_LAST_ADDRESS = "register_last_address"
CONF_REGISTER_VALUE = "register_value"
CONF_VALUE_TYPE = "value_type"
CONF_SERVER_COURTESY_RESPONSE = "server_courtesy_response"
