name: Lint

on:
  push:
    # On other branches the `pull_request` trigger will be used
    branches: [current, next]

  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install pagefind
      uses: jaxxstorm/action-install-gh-release@v2.1.0
      with:
          repo: cloudcannon/pagefind
    - uses: actions/checkout@v5.0.0
    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: 3.12
    - name: Install dependencies
      run: pip install -r requirements.txt -r requirements_test.txt
    - name: Register problem matchers
      run: |
        echo "::add-matcher::.github/workflows/matchers/ci-custom.json"
    - name: markdownlint-cli
      uses: nosborn/github-action-markdown-cli@v3.5.0
      with:
        config_file: ".markdownlintrc"
        files: .
    - name: Lint
      run: python lint.py
